athenianco/athenian-api

- .gitignore
- spec/openapi.yaml
> Add the initial metrics API definition

- DEPLOYMENT.md
- README.md
- server/athenian/api/__init__.py
Addresses https://athenianco.atlassian.net/browse/ENG-52
> Add the deployment docs

- .travis.yml
- Dockerfile
> Basic test of the docker image

- server/athenian/api/__init__.py
- server/athenian/api/controllers/status.py
- server/requirements.txt
> Add /status

- .travis.yml
> Fix the deployment

- .travis.yml
> Retag the image after deploying to preserve the cache

- Makefile
according to https://github.com/athenianco/ci/pull/1 it will be mandatory
> Makefile -> add PROJECT variable

- .travis.yml
- server/athenian/api/controllers/metrics.py
- server/athenian/api/openapi/openapi.yaml
- server/tests/test_metrics_controller.py
> Rename /metrics -> /metrics_line

- Dockerfile
- server/README.md
- server/tests/conftest.py
> Allow easy generation of the sample metadata DB

- DEPLOYMENT.md
- server/athenian/api/__init__.py
- server/athenian/api/auth.py
- server/requirements.txt
For now the Auth is optional and is enabled by setting `AUTH0_DOMAIN` and `AUTH0_AUDIENCE` as mentioned in the `DEPLOYMENT`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/20)
> Add authentication with Auth0

- server/README.md
With only these three commands I could run the API successfully.
I documented how to build the image instead of pulling it because the image is not public.
> Doc how to locally run with docker

- server/athenian/api/__init__.py
> Add the graceful exit

- .travis.yml
have to merge https://github.com/athenianco/ci/pull/3 first
> [WIP] push tag latest

- Makefile
- server/README.md
Address @se7entyse7en [suggestion](https://github.com/athenianco/athenian-api/pull/22#discussion_r360259776) about building and running the API image locally using make commands
> Dpordomingo docs local docker

- .travis.yml
> fix deploy failure

- server/athenian/api/controllers/features/metric.py
- server/athenian/api/models/web/metric_id.py
- server/tests/controllers/test_metrics_controller.py
> Fix the zero metric value edge cases

- server/athenian/api/models/web/granularity.py
- server/tests/controllers/test_metrics_controller.py
> Test daily and monthly granularity, too

- Makefile
> Fix the Makefile deps

- server/athenian/api/controllers/miners/github/pull_request.py
- server/athenian/api/models/web/calculated_metric_values.py
- server/athenian/api/serialization.py
- server/tests/controllers/test_metrics_controller.py
> Fix negative metric values

- server/tests/controllers/test_metrics_controller.py
> Check nonzero values in the metric tests

- server/athenian/api/controllers/miners/github/pull_request.py
- server/tests/controllers/test_metrics_controller.py
> Filter timestamps by the ending date

- server/athenian/api/controllers/features/github/pull_request.py
- server/athenian/api/controllers/features/metric.py
- server/athenian/api/serialization.py
- server/tests/controllers/features/github/test_pull_request.py
- server/tests/controllers/test_metrics_controller.py
> Change the timedelta and datetime formatting, add null-s

- server/athenian/api/controllers/reposet_controller.py
- server/tests/controllers/test_repository_set_controller.py
> Handle missing reposet IDs better

- server/athenian/api/async_read_sql_query.py
- server/athenian/api/controllers/metrics_controller.py
- server/athenian/api/controllers/miners/github/pull_request.py
- server/athenian/api/models/web/for_set.py
- server/athenian/api/models/web/invalid_request_error.py
- server/tests/controllers/test_metrics_controller.py
> Fix handling empty SQL resultsets

- server/athenian/api/__init__.py
- server/athenian/api/controllers/metrics_controller.py
- server/athenian/api/controllers/reposet.py
- server/athenian/api/controllers/reposet_controller.py
- server/athenian/api/openapi/openapi.yaml
- server/tests/controllers/test_metrics_controller.py
> Support reposets in /metrics_line

- server/athenian/api/models/state/README.md
- server/athenian/api/models/state/__main__.py
> Add OFFLINE migrations

- server/athenian/api/__init__.py
- server/athenian/api/auth.py
- server/athenian/api/controllers/reposet.py
- server/athenian/api/controllers/reposet_controller.py
- server/athenian/api/controllers/user_controller.py
- server/athenian/api/openapi/openapi.yaml
- server/tests/controllers/conftest.py
- server/tests/controllers/test_user.py
- server/tests/sample_db_data.py
> Add /v1/user and change the user object

- .travis.yml
> Name the testing stages

- server/athenian/api/__init__.py
- server/athenian/api/metadata.py
- server/athenian/api/models/state/__init__.py
> Check the state DB schema version at startup

- server/requirements.txt
> Pin sqlalchemy version in the requirements

- DEPLOYMENT.md
- Makefile
- server/athenian/api/__init__.py
- server/athenian/api/auth.py
> Add the mgmt Auth0 capabilities

- server/athenian/api/slogging.py
> Fix the logs formatting

- server/athenian/api/models/state/models.py
- server/athenian/api/models/state/versions/a8d2bdb184f0_create_invitations_table.py
> Remove user_id fk from the invitations table

- .travis.yml
> Test migrations on SQLite

- server/athenian/api/auth.py
- server/requirements.txt
- server/tests/controllers/test_invitation_controller.py
- server/tests/controllers/test_user_controller.py
Fixes https://sentry.io/organizations/athenianco/issues/1466357502
> Gracefully handle Auth0 mgmt API rate limit

- server/athenian/api/__init__.py
- server/athenian/api/serialization.py
> Gracefully handle DB connectivity problems

- server/athenian/api/models/state/__main__.py
- server/tests/gen_sqlite_db.py
> Fix the state fixture generation

- server/athenian/api/auth.py
> Make nicer auth error messages

- server/athenian/api/controllers/features/github/pull_request_metrics.py
- server/athenian/api/controllers/miners/github/pull_request.py
- server/athenian/api/models/web/metric_id.py
- server/athenian/api/openapi/openapi.yaml
- server/tests/controllers/features/github/test_pull_request.py
- server/tests/controllers/miners/github/test_pull_request.py
> Remove first review

- Makefile
Add 'ATHENIAN_INVITATION_URL_PREFIX' to generated '.env'
> Add ATHENIAN_INVITATION_URL_PREFIX to generated .env

- Makefile
- server/athenian/api/__init__.py
- server/athenian/api/metadata.py
- server/tests/conftest.py
- server/tests/gen_sqlite_db.py
> Fix rebuilding the DBs if .env gets updated

- server/athenian/api/controllers/filter_controller.py
- server/tests/controllers/test_filter_controller.py
> Remove the empty user from /filter/contributors

- server/athenian/api/auth.py
> Fix the premature mgmt token expiration

- Makefile
blocked by https://github.com/athenianco/ci/pull/4
> add required static field to be sent over pubsub

- .travis.yml
related to https://github.com/athenianco/ci/pull/4
> ci -> change condition on deploy

- server/README.md
- server/tests/conftest.py
> Add the ability to run tests on an external metadata DB

- server/athenian/api/controllers/reposet_controller.py
> Fix reposet creation to correctly handle missing installation id

- server/athenian/api/openapi/openapi.yaml
Signed-off-by: David Pordomingo <david.pordomingo.f@gmail.com>
> Enhance docs. Done stage reflects released and closed PRs

- .travis.yml
1) restrict deploy on push to master branch
2) remove commit hash from docker image tag
> ci -> tweaks

- server/athenian/api/controllers/invitation_controller.py
- server/tests/controllers/test_invitation_controller.py
I bumped into this by using an empty `state` db and using the admin invitation link.
> Fix first account creation

- server/athenian/api/controllers/miners/github/release.py
> Allow some time between the PR merge and release timestamps

- server/athenian/api/controllers/miners/github/release.py
> Do not crash on releasing on incomplete branches

- server/athenian/api/openapi/openapi.yaml
Add docs for `review_happened` and sort them according to the enum order
> Add docs for review_happened

- server/athenian/api/__init__.py
> rename env NODE_NAME -> SERVER_NAME

- server/athenian/api/controllers/features/cached_released.py
> Version released PRs cache

- server/athenian/api/controllers/miners/github/pull_request.py
- server/athenian/api/controllers/miners/github/release.py
> Bump cache versions

- server/athenian/api/cache.py
- server/tests/test_cache.py
> Handle cache serialization failures

- server/athenian/api/controllers/features/cached_released.py
- server/athenian/api/controllers/features/entries.py
- server/tests/controllers/features/github/test_cached_released.py
> Include release settings in the released PRs cache

- server/athenian/api/invite_admin.py
- server/tests/test_invite_admin.py
> Check the state DB schema in invite_admin

- server/athenian/api/controllers/features/entries.py
- server/athenian/api/controllers/features/github/pull_request.py
- server/athenian/api/controllers/features/github/pull_request_metrics.py
- server/athenian/api/controllers/miners/github/pull_request.py
- server/tests/controllers/features/github/test_pull_request_filter.py
> Fix the differences between pr-all-count and /filter/pull_requests ENG-752

- docker-compose.yaml
Closes [ENG-804](https://athenianco.atlassian.net/browse/ENG-804).
> Precompdb compose migration

- server/tests/models/test_migrations.py
This test was causing some troubles when I run it locally.
> Make test_migration run fine locally for OSX as well

- server/athenian/api/controllers/contributors_controller.py
- server/athenian/api/controllers/team_controller.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/contributor.py
- server/athenian/api/models/web/team.py
- server/athenian/api/models/web/team_create_request.py
- server/athenian/api/models/web/team_update_request.py
- server/athenian/api/openapi/openapi.yaml
> Add spec for team endpoints

- server/athenian/api/hacks/reproduce_bug.py
I am adding this code after being one millimeter away from formatting our production databases in the unit tests.
> Add the bug reproduction playground ENG-855

- Makefile
- docker-compose.yaml
- server/README.md
> Add a simpler way to run tests locally targeting postgres

- Makefile
> Fix port for pg override instance for local testing

- server/athenian/api/controllers/contributors_controller.py
- server/athenian/api/controllers/team_controller.py
- server/athenian/api/openapi/openapi.yaml
- server/tests/controllers/test_team_controller.py
> Implement the /team/create endpoint ENG-859

- server/athenian/api/controllers/contributors_controller.py
- server/athenian/api/controllers/filter_controller.py
- server/athenian/api/controllers/metrics_controller.py
- server/athenian/api/controllers/miners/github/users.py
- server/athenian/api/controllers/reposet_controller.py
- server/athenian/api/controllers/team_controller.py
- server/athenian/api/openapi/openapi.yaml
- server/athenian/api/response.py
- server/tests/controllers/test_team_controller.py
> Implement the `/teams/{id}` endpoint ENG-859

- server/tests/load_postgres_data.py
> test -> load_postgres_data.py -> add pass env check

- server/tests/load_postgres_data.py
> test -> load_postgres_data.py -> pg_dump -> add --no-owner flag

- docker-compose.yaml
> Update pg version in docker-compose file

- server/athenian/api/hacks/heat_cache.py
[DEV-256]
[DEV-256]: https://athenianco.atlassian.net/browse/DEV-256
> Do not crash the heater completely DEV-256

- server/athenian/api/controllers/filter_controller.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/filter_contributors_request.py
- server/athenian/api/openapi/openapi.yaml
Partially addresses [DEV-224](https://athenianco.atlassian.net/browse/DEV-224).
This PR just adds the model and uses it. The change is backward compatible.
> Filter contribs with param

- server/athenian/api/controllers/filter_controller.py
- server/athenian/api/controllers/miners/github/contributors.py
- server/tests/controllers/miners/github/test_contributors.py
- server/tests/controllers/test_filter_controller.py
Closes [DEV-224](https://athenianco.atlassian.net/browse/DEV-224).
This is rebased on #445.
> Mine contribs with param

- Dockerfile
- prometheus_client.patch
Hopefully, to be merged upstream: https://github.com/prometheus/client_python/pull/564
> [DEV-425] Fix broken unicode errors in prometheus_client

- server/athenian/api/controllers/miners/github/commit.py
- server/tests/controllers/test_filter_controller.py
Closes [DEV-476](https://athenianco.atlassian.net/browse/DEV-476).
> Fix filter commits endpoint caching

- .travis.yml
- Dockerfile
- server/setup.py
https://github.com/pypa/setuptools/issues/2350
> [DEV-789] Fix docker builds

- server/athenian/api/controllers/features/histogram.py
Closes [DEV-960](https://athenianco.atlassian.net/browse/DEV-960).
> Fix bins calculation from ticks

- server/athenian/api/controllers/histograms_controller.py
- server/tests/controllers/test_histograms_controller.py
Closes [DEV-961](https://athenianco.atlassian.net/browse/DEV-961).
> Fix the serialization of PRs histograms when building CalculatedPullRequestHistogram

- server/athenian/api/controllers/miners/github/repositories.py
- server/tests/conftest.py
- server/tests/controllers/test_filter_controller.py
https://athenian.slack.com/archives/C01AZUJGZRN/p1604604927019800
> [DEV-1129] Fix the exposure of all repositories when all are released by branch

- server/athenian/api/defer.py
> Handle current transaction being `None`

- server/athenian/api/controllers/miners/github/precomputed_prs.py
- server/athenian/api/controllers/miners/github/release_mine.py
- server/athenian/api/hacks/heat_cache.py
- server/tests/controllers/miners/github/test_precomputed_prs.py
They will be marked as force push dropped in the next step anyway.
> [DEV-1394] Delete force push dropped PRs in the heater

- server/athenian/api/controllers/miners/github/commit.py
This reverts commit 8f33a8cbfb5c1a8009916587f584a6f91833998b.
> [DEV-1409] Revert "Revert back the recursive SQL to fetch the commit DAG"

- server/athenian/api/connexion.py
[![Beastire Boys - Sabotage](https://img.youtube.com/vi/z5rRZdiu1UE/0.jpg)](https://www.youtube.com/watch?v=z5rRZdiu1UE)
> [DEV-1699] Sabotage!

- server/tests/load_pg_data.sh
> test -> load_postgres_data.py -> dump persistentdata

- docker-compose.yaml
- server/tests/load_pg_data.sh
Closes [DEV-1970](https://athenianco.atlassian.net/browse/DEV-1970).
This is blocked until the new image for pre-staging is rebuild with the environment variable described [DEV-1971](https://athenianco.atlassian.net/browse/DEV-1971). \cc @lwsanty
> [DEV-1970] Compose provided dumps

- server/athenian/api/controllers/calculator_selector.py
- server/athenian/api/controllers/histograms_controller.py
- server/athenian/api/controllers/metrics_controller.py
- server/athenian/api/controllers/status_controller.py
- server/tests/controllers/test_cors.py
Closes [DEV-2194](https://athenianco.atlassian.net/browse/DEV-2194).
> Add X-Metrics-Calculator response header

- .github/workflows/push.yml
- server/athenian/api/__main__.py
- server/athenian/api/connexion.py
- server/athenian/api/controllers/features/entries.py
- server/athenian/api/controllers/features/github/unfresh_pull_request_metrics.py
- server/athenian/api/controllers/miners/github/pull_request.py
- server/athenian/api/controllers/miners/github/release_match.py
- server/athenian/api/controllers/pagination_controller.py
- server/athenian/api/experiments/preloading/entries.py
- server/athenian/api/preloading/cache.py
- server/tests/conftest.py
- server/tests/controllers/miners/github/test_pull_request.py
- server/tests/sample_db_data.py
Closes [DEV-2147](https://athenianco.atlassian.net/browse/DEV-2147).
> Preloading fetch prs

- server/athenian/api/experiments/preloading/entries.py
- server/athenian/api/preloading/cache.py
Rationale: if I hold Ctrl and click `prs` in `MCID`, I immediately jump to the usages of that cached table in PyCharm.
> Refactor MemoryCache to remove string constant IDs

- server/athenian/api/controllers/features/entries.py
- server/athenian/api/controllers/miners/github/branches.py
- server/athenian/api/experiments/preloading/entries.py
- server/athenian/api/preloading/cache.py
Closes [DEV-2305](https://athenianco.atlassian.net/browse/DEV-2305).
> Preload branches

- server/athenian/api/experiments/preloading/entries.py
- server/athenian/api/preloading/cache.py
Closes [DEV-2306](https://athenianco.atlassian.net/browse/DEV-2306).
Depends on [this](https://github.com/athenianco/athenian-api/pull/1419).
> Preload release match timespan

- server/athenian/api/controllers/features/github/unfresh_pull_request_metrics.py
- server/athenian/api/controllers/miners/github/precomputed_prs.py
- server/athenian/api/experiments/preloading/entries.py
- server/athenian/api/preloading/cache.py
Closes [DEV-2311](https://athenianco.atlassian.net/browse/DEV-2311).
Depends on [this](https://github.com/athenianco/athenian-api/pull/1420).
> Preload open prs facts

- server/athenian/api/controllers/features/everything.py
- server/athenian/api/controllers/features/github/pull_request_filter.py
- server/athenian/api/controllers/features/github/unfresh_pull_request_metrics.py
- server/athenian/api/controllers/miners/github/precomputed_prs/__init__.py
- server/athenian/api/controllers/miners/github/precomputed_prs/merged_prs.py
- server/athenian/api/controllers/miners/github/pull_request.py
- server/athenian/api/controllers/miners/github/release_match.py
- server/athenian/api/experiments/preloading/entries.py
- server/athenian/api/preloading/cache.py
- server/tests/conftest.py
- server/tests/controllers/miners/github/test_precomputed_prs.py
- server/tests/controllers/miners/github/test_pull_request.py
Closes [DEV-2312](https://athenianco.atlassian.net/browse/DEV-2312).
Depends on #1434.
> Preload prs merged facts

- server/athenian/api/preloading/cache.py
- server/tests/conftest.py
- server/tests/controllers/features/github/test_pull_request_metrics.py
- server/tests/controllers/miners/github/test_pull_request.py
- server/tests/controllers/miners/github/test_release.py
I realized I missed fixing the tests for `PullRequestMiner`.
> Ensure that PreloadedPullRequestMiner is used when testing with preloading enabled

- .github/workflows/push.yml
- server/athenian/api/__main__.py
- server/athenian/api/controllers/events_controller.py
- server/athenian/api/controllers/features/entries.py
- server/athenian/api/controllers/features/everything.py
- server/athenian/api/controllers/features/github/pull_request_filter.py
- server/athenian/api/controllers/jira_controller.py
- server/athenian/api/controllers/miners/github/commit.py
- server/athenian/api/controllers/miners/github/precomputed_prs/__init__.py
- server/athenian/api/controllers/miners/github/precomputed_prs/done_prs.py
- server/athenian/api/controllers/miners/github/precomputed_prs/merged_prs.py
- server/athenian/api/controllers/miners/github/precomputed_prs/open_prs.py
- server/athenian/api/controllers/miners/github/precomputed_releases.py
- server/athenian/api/controllers/miners/github/release_match.py
- server/athenian/api/controllers/miners/jira/issue.py
- server/athenian/api/controllers/pagination_controller.py
- server/athenian/api/controllers/settings_controller.py
- server/athenian/api/db.py
- server/athenian/api/experiments/preloading/entries.py
- server/athenian/api/hacks/heat_cache.py
- server/athenian/api/hacks/push_copy_releases.py
- server/athenian/api/invite_admin.py
- server/athenian/api/models/__init__.py
- server/athenian/api/preloading/__main__.py
- server/athenian/api/preloading/cache.py
- server/tests/conftest.py
- server/tests/controllers/miners/github/test_precomputed_prs.py
Closes [DEV-2307](https://athenianco.atlassian.net/browse/DEV-2307).
Depends on #1449.
> Preload prs done facts

- server/athenian/api/aiocron.py
- server/requirements.txt
First step for addressing [DEV-2239](https://athenianco.atlassian.net/browse/DEV-2239).
> Aiocron copy

- server/athenian/api/aiocron.py
This depends on [this](https://github.com/athenianco/athenian-api/pull/1527).
This is a step towards solving [DEV-2239](https://athenianco.atlassian.net/browse/DEV-2239).
> Add aiocron with probabilistic early expiration

- server/athenian/api/__main__.py
- server/athenian/api/aiocron.py
- server/athenian/api/preloading/cache.py
- server/tests/conftest.py
Closes [DEV-2239](https://athenianco.atlassian.net/browse/DEV-2239).
> Preloading refresh

- server/athenian/api/controllers/calculator_selector.py
- server/athenian/api/controllers/features/entries.py
- server/athenian/api/experiments/preloading/entries.py
- server/athenian/api/preloading/cache.py
- server/tests/controllers/features/test_entries.py
- server/tests/controllers/test_calculator_selector.py
- server/tests/experiments/test_preloading.py
Closes [DEV-2513](https://athenianco.atlassian.net/browse/DEV-2513).
Depends on [this](https://github.com/athenianco/athenian-api/pull/1536).
> No preloading if not ready

- server/athenian/api/preloading/cache.py
Closes [DEV-2129](https://athenianco.atlassian.net/browse/DEV-2129).
> [DEV-2129] Prometheus preloading timing

- server/athenian/api/controllers/calculator_selector.py
- server/tests/controllers/test_calculator_selector.py
Closes [DEV-2322](https://athenianco.atlassian.net/browse/DEV-2322).
> [DEV-2322] Calculators caching

- docker-compose.yaml
https://docs.docker.com/compose/compose-file/compose-file-v2/#entrypoint
related to [[DEV-3558]]
[DEV-3558]: https://athenianco.atlassian.net/browse/DEV-3558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docker-compose -> V2 compatible

- server/athenian/api/cache.py
- server/athenian/api/tracing.py
This way it also works in pytest.
> [DEV-3672] Replace __traceback_hide__ with __tracebackhide__

- server/athenian/api/controllers/settings_controller.py
- server/tests/controllers/test_settings_controller.py
While inspecting code for DEV-3911 I spotted a problem on logical deployments cleaning.
Also a small refactor has been done to reduce code duplication.
> [DEV-3911] logical repo fix clean deployments

- server/athenian/api/controllers/settings_controller.py
- server/pyproject.toml
- server/requirements-test.txt
- server/tests/controllers/test_settings_controller.py
- server/tests/testutils/db.py
- server/tests/testutils/factory.py
- server/tests/testutils/factory_alchemy.py
The resolution of DEV-3911 after extra bug-fixing.
* Delete prs and releases facts about physical repo when logical repo changes
* Add some model factories to make tests more brief, using https://factoryboy.readthedocs.io/en/stable/
> [DEV-3911] logical repo change clean related facts

- server/athenian/api/controllers/miners/github/release_load.py
Add some hints to the fetch tag releases query.
> [DEV-4004] Add planner hints to optimize releases fetch

- server/athenian/api/__main__.py
- server/athenian/api/precompute/__main__.py
- server/athenian/api/precompute/accounts.py
- server/tests/precompute/conftest.py
- server/tests/precompute/test_accounts.py
- server/tests/precompute/test_discover_accounts.py
Sample trace produced:
https://sentry.io/organizations/athenianco/performance/api:1e3454fb658349f4af348aed106d7eac/?environment=development&project=1867351&query=transaction.duration%3A%3C15m&statsPeriod=14d&transaction=precomputer%5Baccounts%5D&unselectedSeries=p100%28%29
Update sample:
https://sentry.io/organizations/athenianco/performance/api:2f772133ae7b4cf2ad0ff26f4471fc69/?environment=development&project=1867351&query=transaction.duration%3A%3C15m&showTransactions=recent&statsPeriod=24h&transaction=precomputer%5Baccounts%5D&unselectedSeries=p100%28%29
> [DEV-4088] precomputer send traces to sentry

- server/athenian/api/align/goals/templates.py
Imported from 
https://github.com/athenianco/athenian-webapp/blob/master/src/js/align/pages/goal/config.ts#L64
> [DEV-4265] Define templates for align

- server/athenian/api/serialization.py
- server/tests/align/mutations/test_goals.py
- server/tests/align/queries/test_metrics.py
- server/tests/align/scalars/test_date.py
- server/tests/test_serialization.py
This is especially needed when creating a goal for the next year.
> [DEV-4463] Accept dates in the future in graphql

- server/athenian/api/internal/account.py
This reverts commit 8350116bfac898bfc7395ac709467c6f590e0489, reversing
changes made to 1941dd705f3a1b300f30f185c1c5839805b0f608.
> Revert "Merge pull request #2538 from athenianco/hack-to-precompute-279"

- server/athenian/api/internal/miners/github/release_mine.py
This is faster than ANY VALUES ...
> [DEV-4568] Use JOIN VALUES in commits query in mine_releases

- .github/workflows/push.yml
- server/athenian/api/models/state/check_sdb_migrations.sh
- server/athenian/api/models/state/models.py
- server/athenian/api/models/state/versions/9172948308c9_drop_table_jira_identity_mapping_old.py
- server/requirements-test.txt
Run CI with pull_request event here
https://github.com/athenianco/athenian-api/runs/7547122214?check_suite_focus=true
https://github.com/athenianco/athenian-api/runs/7574761678?check_suite_focus=true
> [DEV-4663] align sdb models to migrations

- server/athenian/api/align/goals/dbaccess.py
- server/athenian/api/align/queries/goals.py
- server/tests/align/goals/test_dbaccess.py
- server/tests/align/queries/test_goals.py
Fallback was not considered for teams not assigned to the goal but for
which the metrics must be computed.
> [DEV-4803] Handle Goal repositories fallback in GraphQL goals query

- server/athenian/api/internal/miners/github/repository.py
- server/athenian/api/internal/settings.py
- server/athenian/api/models/state/check_sdb_migrations.sh
- server/tests/controllers/test_settings_controller.py
First part of #2648 including only tech debt stuff
> [DEV-3862] set release matches remove dead code

- .github/workflows/push.yml
- Makefile
- docker-compose.yaml
> [DEV-4912] support Artifacts Registry

- server/athenian/api/controllers/settings_controller.py
- server/athenian/api/internal/settings.py
- server/athenian/api/models/state/backfill_release_settings_repo_id_logical_name.py
- server/athenian/api/models/state/models.py
- server/athenian/api/models/state/versions/9b386094fab9_releasesettings_repo_id.py
- server/tests/controllers/conftest.py
- server/tests/controllers/test_settings_controller.py
- server/tests/testutils/factory/state.py
First part of release settings repo id:
* models
* backfill script
* write also new columns when a release settings row is inserted
> [DEV-3862] add repository id to release settings

- docker-compose.yaml
- server/athenian/api/internal/miners/github/deployment.py
- server/tests/internal/miners/github/test_deployment.py
I think we have a fact about a deleted repo in pdb, now this is ignored
> [DEV-5027] hide outlier deploys handle unknown repo

- server/athenian/api/auth.py
- server/athenian/api/models/web/jira_status.py
- server/tests/precompute/test_accounts.py
Need API implementing https://github.com/athenianco/api-spec/pull/114 to pass CI, due to concurrent spec update
> [DEV-5072] fix jira issue status no category

- server/athenian/api/align/goals/dbaccess.py
- server/athenian/api/align/models.py
- server/athenian/api/align/mutations/goals.py
- server/athenian/api/models/web/__main__.py
- server/tests/align/goals/test_dbaccess.py
- server/tests/align/mutations/test_goals.py
- server/tests/controllers/goal_controller/test_goal.py
rationale here
https://github.com/athenianco/private-api-spec/pull/65
> [DEV-5294] gql update goal team metric params

- server/athenian/api/controllers/search_controller.py
- server/athenian/api/controllers/search_controller/__init__.py
- server/athenian/api/controllers/search_controller/search_prs.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/search_prs.py
- server/athenian/api/request.py
- server/tests/controllers/search_controller/test_search_prs.py
- server/tests/testutils/factory/metadata.py
- server/tests/testutils/factory/wizards.py
The "basic" implementation of /search/pull_requests.
Propagate already supported filters to PRFactsCalculator and compose the result.
> [DEV-5347] search prs basic

- server/athenian/api/application.py
Avoid yaml parsing of the spec for every test.
```
$ pytest -q  'tests/controllers/test_team_controller.py'
56 passed, 2 warnings in 28.85s
$ git checkout DEV-4331-speedup-tests
$ pytest -q  'tests/controllers/test_team_controller.py'
56 passed, 2 warnings in 17.10s
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3119)
> [DEV-4331] speedup tests

- server/athenian/api/controllers/integrations_controller.py
- server/tests/controllers/test_integrations_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3121)
> [DEV-5508] Allow default user in match_identities controller

- server/athenian/api/internal/miners/github/deployment.py
- server/athenian/api/internal/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3123)
> [DEV-5513] Do not crash in mining deployments of repositories outside of the reposet

- server/athenian/api/internal/features/github/deployment_metrics.py
- server/tests/controllers/features/github/test_deployment_metrics.py
- server/tests/internal/features/github/test_deployment_metrics.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3124)
> [DEV-5480] Fix group by repo for deployment metrics

- server/athenian/api/controllers/goal_controller.py
- server/tests/controllers/align/test_metric_controller.py
- server/tests/controllers/goal_controller/test_goal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3122)
> [DEV-5399] spec metric params validation

- .github/workflows/push.yml
- server/athenian/api/application.py
- server/tests/test_heavy_load.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3128)
> [DEV-5503] Use 32-core GHA runners to execute the test suite

- server/athenian/api/controllers/dashboard_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3129)
> [DEV-5519] Add dashboard controllers stubs

- server/athenian/api/controllers/dashboard_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3131)
> [DEV-5519] Fix dashboard controller stubs

- server/athenian/api/internal/miners/github/branches.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3133)
> [DEV-5541] Measure branch health metrics

- server/athenian/api/application.py
- server/tests/test_spec.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3134)
> [DEV-5555] Fix spec template render

- .github/workflows/push.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3135)
> [DEV-5554] fix forks prs to avoid usage of large runners

- server/athenian/api/internal/data_health_metrics.py
- server/athenian/api/internal/features/entries.py
- server/athenian/api/internal/miners/github/branches.py
- server/athenian/api/internal/miners/github/commit.py
- server/athenian/api/internal/miners/github/deployment.py
- server/athenian/api/internal/miners/github/deployment_light.py
- server/athenian/api/internal/miners/github/release_load.py
- server/athenian/api/internal/miners/github/release_match.py
- server/athenian/api/internal/miners/github/release_mine.py
- server/athenian/api/internal/reposet.py
- server/athenian/api/precompute/accounts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3136)
> [DEV-5541] Measure the internal data health metrics

- server/athenian/api/models/state/models.py
- server/athenian/api/models/state/versions/a0c659e45929_dashboards.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3130)
> [DEV-5532] Define dashboard related DB models

- server/athenian/api/internal/data_health_metrics.py
- server/athenian/api/internal/features/entries.py
- server/athenian/api/internal/miners/github/branches.py
- server/athenian/api/internal/miners/github/commit.py
- server/athenian/api/internal/miners/github/deployment.py
- server/athenian/api/internal/miners/github/release_load.py
- server/athenian/api/internal/reposet.py
- server/athenian/api/models/persistentdata/models.py
- server/athenian/api/models/persistentdata/versions/41fcc01cccc0_add_health_metrics_table.py
- server/athenian/api/precompute/__main__.py
- server/athenian/api/precompute/accounts.py
- server/tests/precompute/test_accounts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3140)
> [DEV-5541] Persist account data health metrics in rdb

- server/athenian/api/controllers/backoffice_controller.py
- server/athenian/api/controllers/metrics_controller.py
- server/athenian/api/internal/features/entries.py
- server/athenian/api/internal/miners/github/release_mine.py
- server/athenian/api/precompute/__main__.py
- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3151)
> [DEV-5541] Record inconsistency and performance metrics in precomputer

- server/athenian/api/application.py
- server/athenian/api/controllers/backoffice_controller.py
- server/athenian/api/internal/data_health_metrics.py
- server/athenian/api/internal/datetime_utils.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/account_health.py
- server/athenian/api/models/web/accounts_health.py
- server/athenian/api/models/web/calculated_code_check_metrics_item.py
- server/athenian/api/models/web/calculated_linear_metric_values.py
- server/athenian/api/models/web/calculated_pull_request_metrics_item.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3152)
> [DEV-5540] Implement /account/health logic

- server/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3153)
> Upgrade mimalloc and remove the patch

- server/athenian/api/controllers/metrics_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3154)
> [DEV-5521] metrics controller typing fixes

- server/athenian/api/precompute/accounts.py
- server/athenian/api/precompute/store_external_health.py
- server/tests/controllers/miners/github/test_branches.py
- server/tests/controllers/miners/github/test_commit.py
- server/tests/controllers/miners/github/test_release.py
- server/tests/controllers/test_filter_controller.py
- server/tests/internal/features/test_entries.py
- server/tests/internal/miners/github/test_deployment.py
- server/tests/precompute/test_accounts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3155)
> [DEV-5569] Add unit tests for internal account data health metrics

- server/athenian/api/controllers/filter_controller.py
- server/tests/controllers/filter_controller/test_get_prs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3156)
> [DEV-5574] get prs fix missing include users

- server/athenian/api/internal/data_health_metrics.py
- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3157)
> [DEV-5541] Record pending fetch metadata metrics

- server/athenian/api/align/goals/dates.py
- server/athenian/api/align/goals/measure.py
- server/athenian/api/align/mutations/goals.py
- server/athenian/api/controllers/align/metric_controller.py
- server/athenian/api/controllers/dashboard_controller.py
- server/athenian/api/controllers/goal_controller.py
- server/athenian/api/internal/dashboard.py
- server/athenian/api/internal/datetime_utils.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/dashboard.py
- server/tests/align/goals/test_dates.py
- server/tests/controllers/dashboard_controller/test_get_dashboard.py
- server/tests/controllers/search_controller/test_search_prs.py
- server/tests/internal/test_dashboard.py
- server/tests/internal/test_datetime_utils.py
- server/tests/testutils/factory/state.py
- server/tests/testutils/requester.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3158)
> [DEV-5519] get dashboard controller

- server/athenian/api/metadata.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3159)
> Start 0.18.x

- server/athenian/api/auth.py
- server/athenian/api/controllers/backoffice_controller.py
- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3161)
> [DEV-5577] [DEV-5579] Fix flaws in account health

- server/athenian/api/controllers/dashboard_controller.py
- server/athenian/api/internal/dashboard.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/dashboard.py
- server/tests/controllers/dashboard_controller/test_create_dashboard_chart.py
- server/tests/internal/test_dashboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3160)
> [DEV-5521] create dashboard chart controller

- server/athenian/api/controllers/backoffice_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3162)
> [DEV-5583] Fix querying since/until in /account/health

- server/athenian/api/cache.py
- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3167)
> [DEV-5561] Put cache get timeout

- server/athenian/api/application.py
- server/athenian/api/internal/features/github/unfresh_pull_request_metrics.py
- server/athenian/api/internal/miners/github/deployment.py
- server/athenian/api/internal/miners/github/release_load.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3169)
> [DEV-5561] Add only_applied_matches mode to load_releases()

- .github/workflows/push.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3171)
> [DEV-5603] Replace the test suite with a stub

- server/athenian/api/controllers/dashboard_controller.py
- server/athenian/api/internal/dashboard.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/dashboard.py
- server/tests/controllers/dashboard_controller/test_update_dashboard.py
- server/tests/internal/test_dashboard.py
- server/tests/models/web/test_dashboard.py
- server/tests/testutils/requester.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3172)
> [DEV-5520] update dashboard controller

- .github/workflows/push.yml
- server/tests/conftest.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3175)
> [DEV-5603] Execute the test suite on free runners

- .github/workflows/push.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3176)
> [DEV-5603] Return pull_request_target back

- server/athenian/api/cache.py
- server/athenian/api/segment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3178)
> [DEV-5606] Shield the fetch from memcached in case of a timeout

- server/tests/controllers/filter_controller/test_get_prs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3177)
> [DEV-5596] get prs handle empty result

- server/athenian/api/defer.py
- server/athenian/api/internal/data_health_metrics.py
- server/athenian/api/internal/features/entries.py
- server/athenian/api/precompute/accounts.py
- server/athenian/api/segment.py
- server/tests/internal/features/test_entries.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3170)
> [DEV-5588] Submit health metrics to Segment

- server/athenian/api/precompute/accounts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3179)
> [DEV-5588] Fix the func arg order in health metrics to Segment

- server/athenian/api/internal/miners/github/branches.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3186)
> [DEV-5607] Optimize loading branches from the DB

- server/athenian/api/models/state/models.py
- server/athenian/api/models/state/versions/9c00a6d0e384_dashboard_chart_filters.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3174)
> [DEV-5581] Add filters to dashboard chart DB model

- .github/workflows/push.yml
- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3187)
> [DEV-5609] Do not record inconsistencies for expired accounts

- server/athenian/api/segment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3188)
> [DEV-5616] Avoid updating Last Seen in Intercom on health metrics updates

- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3189)
> [DEV-5609] Add idv2 forced metric

- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3190)
> [DEV-5609] Fix loading idv2 force on staging

- server/athenian/api/internal/miners/github/branches.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3191)
> [DEV-5607] Force Bitmap Scan while loading branches for many repos

- .github/workflows/push.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3192)
> Set a download timeout for actions/cache

- server/athenian/api/__main__.py
- server/athenian/api/async_utils.py
- server/athenian/api/controllers/backoffice_controller.py
- server/athenian/api/precompute/store_external_health.py
- server/athenian/api/slack/performance_report.jinja2
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3193)
> [DEV-5585] Report bad performance in precomputer

- server/athenian/api/precompute/accounts.py
- server/athenian/api/precompute/store_external_health.py
- server/athenian/api/slack/almost_expired.jinja2
- server/athenian/api/slack/bad_health.jinja2
- server/athenian/api/slack/blocked_registration_banished.jinja2
- server/athenian/api/slack/blocked_registration_membership.jinja2
- server/athenian/api/slack/disabled_jira_projects.jinja2
- server/athenian/api/slack/installation_goes_on.jinja2
- server/athenian/api/slack/matched_jira_identities.jinja2
- server/athenian/api/slack/new_account.jinja2
- server/athenian/api/slack/new_installation.jinja2
- server/athenian/api/slack/new_release_event.jinja2
- server/athenian/api/slack/new_user.jinja2
- server/athenian/api/slack/precomputed_account.jinja2
- server/athenian/api/slack/precomputed_failure.jinja2
- server/athenian/api/slack/user_account_expired.jinja2
- server/athenian/api/slack/user_rejected.jinja2
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3195)
> [DEV-5585] Report some very suspicious data health issues

- server/athenian/api/internal/miners/github/deployment.py
- server/athenian/api/precompute/accounts.py
- server/tests/internal/miners/github/test_deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3196)
> [DEV-5482] Exclude deployments with nothing deployed in requested repositories

- server/athenian/api/__main__.py
- server/athenian/api/internal/prefixer.py
- server/athenian/api/internal/reposet.py
- server/athenian/api/precompute/accounts.py
- server/tests/conftest.py
- server/tests/controllers/miners/github/test_pull_request.py
- server/tests/internal/test_reposet.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3197)
> [DEV-5557] Add new repositories to the reposet in precomputer

- server/athenian/api/auth.py
- server/athenian/api/controllers/invitation_controller.py
- server/athenian/api/internal/account.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3198)
> [DEV-5501] Apply minor code edits during the investigation

- server/athenian/api/controllers/events_controller.py
- server/athenian/api/internal/miners/github/pull_request.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3199)
> [DEV-5637] Optimize CPU of filtering PRs

- server/athenian/api/internal/features/github/pull_request_filter.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3200)
> [DEV-5642] Fix filtering 0 PRs

- server/athenian/api/controllers/events_controller.py
- server/tests/controllers/test_events_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3202)
> [DEV-5648] Increase the unresolved deployment notifications GC trigger to 2 weeks

- server/athenian/api/align/goals/templates.py
- server/tests/align/mutations/test_goals.py
Resolved [DEV-5643](https://athenianco.atlassian.net/browse/DEV-5643)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3203)
> [DEV-5643] Rename and reorder goal templates

- server/athenian/api/precompute/accounts.py
- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3204)
> [DEV-5647] Fix the alert on changed done PRs count

- server/athenian/api/unordered_unique.pyx
- server/tests/test_unordered_unique.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3206)
> [DEV-5652] Test empty keys-values in map_array_values()

- server/athenian/api/controllers/dashboard_controller.py
- server/athenian/api/controllers/goal_controller.py
- server/athenian/api/internal/dashboard.py
- server/athenian/api/internal/jira.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/dashboard.py
- server/tests/controllers/dashboard_controller/test_create_dashboard_chart.py
- server/tests/controllers/dashboard_controller/test_get_dashboard.py
- server/tests/internal/test_dashboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3207)
> [DEV-5589] dashboard chart filters

- server/tests/controllers/align/test_metric_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3212)
> [DEV-5665] allow threshold for jira lead time

- server/athenian/api/internal/features/metric_calculator.py
- server/athenian/api/native/sorted_intersection.h
- server/athenian/api/native/sum_repeated_with_step.h
- server/athenian/api/sorted_intersection.pyx
- server/athenian/api/sparse_mask.py
- server/setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3213)
> [DEV-5670] Speedup developer metrics CPU 5x

- server/athenian/api/controllers/filter_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3216)
> [DEV-5682] Use native JSON serializer in /filter/releases

- server/athenian/api/models/state/reimport_goal_templates.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3217)
> [DEV-5643] Add --reset flag to reimport_goal_templates

- server/athenian/api/internal/features/entries.py
- server/athenian/api/internal/prefixer.py
- server/athenian/api/internal/settings.py
- server/tests/controllers/goal_controller/test_measure_goals.py
- server/tests/controllers/test_prefixer.py
- server/tests/internal/features/github/test_pull_request_metrics.py
- server/tests/internal/test_settings.py
- server/tests/testutils/factory/wizards.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3214)
> [DEV-5639] batch calc physical include logical repos

- server/athenian/api/controllers/search_controller/search_prs.py
- server/athenian/api/models/web/search_prs.py
- server/tests/controllers/search_controller/test_search_prs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3219)
> [DEV-5675] search prs order by total stage timing

- server/athenian/api/internal/miners/github/precomputed_releases.py
- server/athenian/api/internal/miners/github/release_mine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3218)
> [DEV-5682] Improve SQL perf of loading release deployments in /filter/releases

- server/athenian/api/controllers/dashboard_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3220)
> [DEV-5696] Fix missing transaction in update_dashboard controller

- server/athenian/api/controllers/jira_controller.py
- server/athenian/api/internal/features/github/pull_request_filter.py
- server/athenian/api/internal/features/github/unfresh_pull_request_metrics.py
- server/athenian/api/internal/miners/github/precomputed_prs/merged_prs.py
- server/athenian/api/internal/miners/github/pull_request.py
- server/tests/controllers/miners/github/test_pull_request.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3221)
> [DEV-5691] Do not load PR deployments twice in /filter/jira

- server/athenian/api/internal/miners/github/branches.py
- server/athenian/api/internal/miners/github/contributors.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3223)
> Optimize loading branches for meta_id 50

- server/athenian/api/controllers/jira_controller.py
- server/athenian/api/controllers/reposet_controller.py
- server/athenian/api/internal/features/github/pull_request_filter.py
- server/athenian/api/internal/miners/github/contributors.py
- server/athenian/api/internal/miners/github/deployment.py
- server/athenian/api/internal/miners/github/deployment_light.py
- server/athenian/api/internal/miners/github/pull_request.py
- server/athenian/api/internal/miners/github/release_load.py
- server/tests/controllers/features/github/test_pull_request_filter.py
- server/tests/controllers/features/github/test_pull_request_metrics.py
- server/tests/controllers/miners/github/test_release.py
- server/tests/controllers/test_filter_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3225)
> [DEV-5701] Include PR base ref merge points in branch releases

- server/athenian/api/internal/miners/github/pull_request.py
- server/tests/controllers/features/github/test_pull_request_metrics.py
- server/tests/controllers/miners/github/test_pull_request.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3226)
> [DEV-5684] Handle the edge case with review request without review in an open PR

- server/athenian/api/internal/miners/github/branches.py
- server/athenian/api/internal/miners/github/precomputed_prs/done_prs.py
- server/athenian/api/internal/miners/github/pull_request.py
- server/athenian/api/internal/miners/github/release_match.py
- server/tests/controllers/miners/github/test_precomputed_prs.py
- server/tests/internal/miners/github/test_release_match.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3228)
> [DEV-5710] Optimize fetching PR commits in the miner

- server/athenian/api/internal/features/entries.py
- server/athenian/api/internal/miners/github/branches.py
- server/athenian/api/internal/miners/github/developer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3229)
> [DEV-5710] Active the unfresh mode on more than 1000 branches

- server/athenian/api/internal/miners/github/release_load.py
- server/tests/controllers/test_filter_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3237)
> [DEV-5719] Do not fetch merge points for repos without branches

- server/athenian/api/internal/miners/jira/epic.py
- server/athenian/api/internal/miners/jira/issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3238)
> [DEV-5725] Optimize loading epics in /filter/jira

- server/athenian/api/internal/miners/github/pull_request.py
- server/athenian/api/internal/miners/github/release_load.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3239)
> [DEV-5719] Fix matching branch releases with irrelevant duplicate commits

- server/athenian/api/async_utils.py
- server/athenian/api/internal/features/github/deployment_metrics.py
- server/athenian/api/internal/features/github/pull_request_filter.py
- server/athenian/api/internal/features/github/pull_request_metrics.py
- server/athenian/api/internal/features/github/release_metrics.py
- server/athenian/api/internal/miners/github/check_run.py
- server/athenian/api/internal/miners/github/deployment.py
- server/athenian/api/internal/miners/github/release_load.py
- server/athenian/api/internal/miners/github/release_mine.py
- server/athenian/api/internal/miners/jira/issue.py
- server/athenian/api/internal/miners/types_accelerated.pyx
- server/athenian/api/internal/settings.py
- server/athenian/api/object_arrays.pyx
- server/athenian/api/typing_utils.py
- server/setup.py
- server/tests/controllers/miners/github/test_check_run_benchmark.py
- server/tests/test_typing_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3241)
> [DEV-5744] Fix CPU performance of post-filtering mined releases

- server/athenian/api/controllers/goal_controller.py
- server/athenian/api/internal/datasources.py
- server/athenian/api/internal/jira.py
- server/athenian/api/models/web/goal_template.py
- server/tests/controllers/goal_controller/test_goal_template.py
- server/tests/internal/test_datasources.py
- server/tests/internal/test_jira.py
- server/tests/models/web/test_goal_template.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3242)
> [DEV-5722] goal templates available field

- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3244)
> [DEV-5754] Fix inconsistency metrics submission

- server/athenian/api/hacks/heal.py
- server/athenian/api/internal/miners/github/commit.py
- server/athenian/api/internal/miners/github/release_load.py
- server/athenian/api/internal/miners/github/release_match.py
- server/athenian/api/internal/miners/github/release_mine.py
- server/athenian/api/kms.py
- server/athenian/api/precompute/__main__.py
- server/athenian/api/precompute/accounts.py
- server/athenian/api/precompute/refetcher.py
- server/requirements.txt
- server/tests/precompute/test_accounts.py
- server/tests/run_static_checks.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3243)
> [DEV-5715] Refetch bad commits in commit DAGs

- server/athenian/api/precompute/__main__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3245)
> [DEV-5715] Move --refetch-topic to `accounts` cmdarg

- server/athenian/api/internal/miners/github/release_mine.py
- server/athenian/api/precompute/refetcher.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3246)
> [DEV-5752] Fix reduce_at() crashing in mine_releases()

- server/athenian/api/controllers/user_controller.py
- server/athenian/api/internal/pentest.py
- server/athenian/api/models/web/account.py
- server/tests/controllers/test_user_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3247)
> [DEV-5723] account details datasources

- server/athenian/api/controllers/backoffice_controller.py
- server/athenian/api/controllers/events_controller.py
- server/athenian/api/controllers/filter_controller.py
- server/athenian/api/controllers/histograms_controller.py
- server/athenian/api/controllers/jira_controller.py
- server/athenian/api/controllers/metrics_controller.py
- server/athenian/api/controllers/pagination_controller.py
- server/athenian/api/controllers/settings_controller.py
- server/athenian/api/hacks/push_copy_releases.py
- server/athenian/api/internal/features/entries.py
- server/athenian/api/internal/features/everything.py
- server/athenian/api/internal/features/github/pull_request_filter.py
- server/athenian/api/internal/miners/github/branches.py
- server/athenian/api/internal/miners/github/commit.py
- server/athenian/api/internal/miners/github/contributors.py
- server/athenian/api/internal/miners/github/developer.py
- server/athenian/api/internal/miners/github/release_mine.py
- server/athenian/api/internal/miners/github/repository.py
- server/athenian/api/internal/team_metrics.py
- server/athenian/api/precompute/accounts.py
- server/requirements.txt
- server/tests/conftest.py
- server/tests/controllers/features/github/test_pull_request_filter.py
- server/tests/controllers/miners/github/test_branches.py
- server/tests/controllers/miners/github/test_pull_request.py
- server/tests/controllers/miners/github/test_release.py
- server/tests/internal/features/test_entries.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3248)
> [DEV-5718] Prepare for precomputed branches

- server/athenian/api/internal/miners/github/branches.py
- server/athenian/api/internal/miners/github/release_match.py
- server/athenian/api/precompute/accounts.py
- server/requirements.txt
- server/tests/conftest.py
- server/tests/controllers/miners/github/test_branches.py
- server/tests/controllers/miners/github/test_pull_request.py
- server/tests/controllers/miners/github/test_release.py
- server/tests/controllers/test_user_controller.py
- server/tests/internal/features/test_entries.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3251)
> [DEV-5718] Activate the precomputed branches by default

- server/athenian/api/internal/features/entries.py
- server/athenian/api/internal/features/github/pull_request_metrics.py
- server/tests/controllers/goal_controller/test_measure_goals.py
- server/tests/internal/features/github/test_pull_request_metrics.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3249)
> [DEV-5772] Fix grouping with one participants groups in batch_calc

- server/athenian/api/internal/miners/github/release_load.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3261)
> [DEV-5792] Defend against broken branch releases

- server/athenian/api/internal/miners/github/branches.py
- server/athenian/api/internal/miners/github/deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3264)
> [DEV-5816] Fix the performance of loading branches for multiaccounts

- server/athenian/api/models/metadata/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3266)
> [DEV-5796] Bump the required metadata schema version

- server/athenian/api/controllers/dashboard_controller.py
- server/tests/controllers/dashboard_controller/test_create_dashboard_chart.py
- server/tests/controllers/dashboard_controller/test_delete_dashboard_chart.py
- server/tests/controllers/dashboard_controller/test_update_dashboard.py
- server/tests/testutils/requester.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3267)
> [DEV-5726] dashboard forbid default user

- server/athenian/api/controllers/security_controller.py
- server/athenian/api/internal/user.py
- server/tests/controllers/test_security_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3268)
> [DEV-5817] create token forbid default user

- server/athenian/api/internal/data_health_metrics.py
- server/athenian/api/internal/team_sync.py
- server/athenian/api/precompute/accounts.py
- server/tests/precompute/test_accounts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3271)
> [DEV-5766] Record team sync metrics

- server/athenian/api/__main__.py
- server/athenian/api/application.py
- server/athenian/api/internal/account.py
- server/athenian/api/internal/features/github/check_run_filter.py
- server/athenian/api/internal/miners/github/commit.py
- server/athenian/api/internal/reposet.py
- server/athenian/api/precompute/__main__.py
- server/athenian/api/precompute/context.py
- server/athenian/api/precompute/discover_accounts.py
- server/requirements.txt
- server/tests/conftest.py
- server/tests/controllers/features/github/test_check_run_filter.py
- server/tests/controllers/features/github/test_pull_request_filter.py
- server/tests/controllers/miners/github/test_release.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3281)
> [DEV-5834] Wrap Postgres queries into transactions

- server/athenian/api/align/mutations/goals.py
- server/athenian/api/controllers/dashboard_controller.py
- server/athenian/api/controllers/goal_controller.py
- server/athenian/api/internal/repos.py
- server/athenian/api/models/state/models.py
- server/athenian/api/models/state/versions/3557bf5f319a_chart_group_by.py
- server/tests/internal/test_account.py
- server/tests/testutils/request.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3282)
> [DEV-5731] chart group by model

- server/athenian/api/controllers/dashboard_controller.py
- server/athenian/api/internal/dashboard.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/dashboard.py
- server/tests/controllers/dashboard_controller/test_create_dashboard_chart.py
- server/tests/controllers/dashboard_controller/test_get_dashboard.py
- server/tests/controllers/dashboard_controller/test_update_dashboard.py
- server/tests/internal/test_dashboard.py
- server/tests/testutils/factory/state.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3283)
> [DEV-5732] chart group by

- server/athenian/api/__main__.py
- server/athenian/api/application.py
- server/athenian/api/controllers/invitation_controller.py
- server/athenian/api/hacks/heal.py
- server/athenian/api/internal/miners/github/commit.py
- server/athenian/api/internal/miners/github/release_load.py
- server/athenian/api/internal/miners/github/release_match.py
- server/athenian/api/internal/miners/github/release_mine.py
- server/athenian/api/internal/refetcher.py
- server/athenian/api/precompute/accounts.py
- server/athenian/api/segment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3284)
> [DEV-5797] Refetch org members on membership check failures

- server/athenian/api/controllers/metrics_controller.py
- server/athenian/api/internal/features/entries.py
- server/athenian/api/internal/miners/filters.py
- server/athenian/api/internal/team_metrics.py
- server/athenian/api/models/web/calculated_linear_metric_values.py
- server/tests/controllers/features/github/test_pull_request_filter.py
- server/tests/controllers/features/github/test_pull_request_metrics.py
- server/tests/internal/features/test_entries.py
- server/tests/internal/miners/test_filters.py
Support more JIRAFilter in calc_pull_requests_metrics_line()
I/O will come later.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3272)
> [DEV-5733] calc pr metrics multiple jira groups

- server/athenian/api/models/persistentdata/models.py
- server/athenian/api/models/persistentdata/versions/e06c9947fbdb_collect_data_from_vitally.py
- server/athenian/api/precompute/__main__.py
- server/athenian/api/precompute/store_external_health.py
- server/athenian/api/precompute/vitally.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3286)
> [DEV-5837] Record info from Vitally in precomputer

- server/athenian/api/precompute/vitally.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3288)
> [DEV-5837] Fix storing Vitally info

- server/athenian/api/__main__.py
- server/athenian/api/application.py
- server/athenian/api/vitally.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3290)
> [DEV-5773] Maintain regularly updated info about accounts from Vitally

- server/athenian/api/auth.py
- server/athenian/api/precompute/vitally.py
- server/athenian/api/vitally.py
- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3291)
> [DEV-5773] Trace VIP accounts unconditionally

- server/athenian/api/auth.py
- server/athenian/api/vitally.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3292)
> [DEV-5773] Handle nulls in mrr to check VIC accounts

- server/athenian/api/controllers/dashboard_controller.py
- server/athenian/api/internal/dashboard.py
- server/athenian/api/models/state/models.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/dashboard.py
- server/tests/controllers/dashboard_controller/test_update_dashboard_chart.py
- server/tests/internal/test_dashboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3293)
> [DEV-5839] update dashboard chart

- server/athenian/api/internal/miners/github/pull_request.py
- server/athenian/api/internal/miners/github/release_load.py
- server/athenian/api/internal/miners/jira/issue.py
- server/athenian/api/typing_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3294)
> [DEV-5778] Do not crash without Sentry

- server/athenian/api/__main__.py
- server/athenian/api/application.py
- server/athenian/api/internal/miners/github/branches.py
- server/athenian/api/models/precomputed/schema_monitor.py
- server/athenian/api/vitally.py
- server/tests/models/test_pdb_schema_monitor.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3295)
> [DEV-5851] Fix crash on deleted repos in precomputed branches

- server/athenian/api/internal/miners/github/deployment.py
- server/tests/test_microintegration.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3296)
> [DEV-5848] Report missing commits in deployments in bulk

- server/athenian/api/auth.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3297)
> [DEV-5856] Add the missing logger to _RequestAccountValidation

- server/Makefile
- server/athenian/api/internal/miners/github/dag_accelerated.pyx
- server/athenian/api/internal/miners/github/deployment.py
- server/athenian/api/precompute/accounts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3298)
> [DEV-5857] Add code to debug float-s in deployed release names

- server/athenian/api/controllers/metrics_controller.py
- server/athenian/api/internal/features/entries.py
- server/tests/controllers/features/github/test_release_metrics.py
- server/tests/controllers/metrics_controller/test_calc_metrics_releases.py
- server/tests/internal/features/test_entries.py
- server/tests/testutils/factory/metadata.py
- server/tests/testutils/factory/wizards.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3299)
> [DEV-5734] metrics calc  release multiple jiras

- server/athenian/api/db.py
- server/athenian/api/internal/miners/github/commit.py
- server/athenian/api/internal/miners/github/dag_accelerated.pyx
- server/tests/controllers/miners/github/test_commit.py
- server/tests/controllers/miners/github/test_pull_request.py
- server/tests/controllers/miners/github/test_release.py
- server/tests/internal/miners/github/test_consistency_torture_commits.py
- server/tests/internal/miners/github/test_release_match.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3300)
> [DEV-5858] Add the second, "full" commit DAG fetch mode

- server/athenian/api/models/web_model_io.pyx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3301)
> [DEV-5849] Apply noticed improvements from the FOSDEM talk

- server/athenian/api/db.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3311)
> [DEV-5884] Re-acquire asyncpg connections on InterfaceError

- server/athenian/api/controllers/metrics_controller.py
- server/athenian/api/models/web/jira_filter.py
- server/tests/controllers/metrics_controller/test_calc_metrics_prs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3313)
> [DEV-5887] Ignore jira object with nothing inside in calc_metrics_prs

- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3314)
> [DEV-5884] Fix PG error handling in pgbouncer transation mode

- server/athenian/api/controllers/metrics_controller.py
- server/athenian/api/internal/features/github/pull_request_filter.py
- server/athenian/api/internal/miners/github/precomputed_prs/merged_prs.py
- server/athenian/api/internal/miners/github/release_mine.py
- server/tests/controllers/miners/github/test_release.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3315)
> [DEV-5883] Fix invalid precomputation of tag_or_branch PRs

- server/athenian/api/internal/miners/filters.py
- server/tests/controllers/metrics_controller/test_calc_metrics_releases.py
- server/tests/internal/miners/test_filters.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3317)
> [DEV-5890] fix metrics releases empty jira

- server/athenian/api/internal/miners/github/release_mine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3318)
> [DEV-5897] Fix the performance of JIRA filtering of releases

- server/athenian/api/internal/miners/github/branches.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3319)
> [DEV-5859] Report zero branches with less noise

- Dockerfile
- patches/cpython_rules.patch
- server/athenian/api/internal/miners/github/branches.py
- server/athenian/api/precompute/accounts.py
- server/athenian/api/slack/bad_health.jinja2
- server/tests/controllers/miners/github/test_branches.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3320)
> [DEV-5904] Alert on broken branches

- server/athenian/api/slack/bad_health.jinja2
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3321)
> [DEV-5904] Fix the health report on Slack

- .github/workflows/push.yml
- server/athenian/api/__main__.py
- server/athenian/api/slack/bad_health.jinja2
- server/tests/conftest.py
- server/tests/precompute/test_accounts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3323)
> [DEV-5904] Test sending health alerts

- server/athenian/api/internal/features/entries.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3322)
> [DEV-5911] Optimize group by repos in batch metrics calculation

- server/athenian/api/internal/miners/github/branches.py
- server/tests/test_microintegration.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3325)
> [DEV-5927] Optimize fetching new branches in the narrow time window

- server/athenian/api/controllers/jira_controller.py
- server/athenian/api/internal/miners/jira/issue.py
- server/athenian/api/models/metadata/jira.py
- server/tests/controllers/test_jira_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3326)
> [DEV-5927] Fast path for fetching jira issue types

- server/athenian/api/internal/miners/jira/issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3327)
> [DEV-5927] Fix the fast path of `/filter/jira`

- server/athenian/api/controllers/dashboard_controller.py
- server/tests/controllers/dashboard_controller/test_update_dashboard_chart.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3328)
> [DEV-5933] Fix update_dashboard_chart with dashboard_id 0

- server/athenian/api/internal/miners/github/developer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3329)
> [DEV-5927] Optimize fetching PR review comments for developer metrics

- server/athenian/api/internal/features/entries.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3330)
> [DEV-5927] Calculate developer metrics in several threads

- server/athenian/api/internal/miners/jira/issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3332)
> [DEV-5936] Hopefully speedup filtering jira issues by epics

- server/athenian/api/internal/features/github/check_run_filter.py
- server/athenian/api/internal/features/github/check_run_metrics.py
- server/athenian/api/internal/miners/github/branches.py
- server/athenian/api/internal/miners/github/check_run.py
- server/athenian/api/internal/miners/github/release_load.py
- server/athenian/api/object_arrays.pyx
- server/tests/controllers/miners/github/test_release.py
- server/tests/test_object_arrays.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3331)
> [DEV-5936] Update branches by repo id + name instead of node IDs

- server/athenian/api/internal/miners/github/branches.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3335)
> [DEV-5936] Fix updating precomputed branches with 0 changed repos

- server/athenian/api/internal/miners/github/pull_request.py
- server/tests/controllers/metrics_controller/test_calc_metrics_prs.py
- server/tests/internal/miners/github/test_pull_request.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3334)
> [DEV-5934] Fix the caching of jira priorities in PullRequestMiner

- server/athenian/api/internal/account.py
- server/athenian/api/precompute/__main__.py
- server/athenian/api/precompute/discover_accounts.py
- server/tests/precompute/test_discover_accounts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3347)
> [DEV-5970] Support setting accounts to discover-accounts + improve logging installation progress

- server/athenian/api/align/goals/templates.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3346)
> [DEV-5550] Add goal templates for wip/merging time threshold metrics

- server/athenian/api/__main__.py
- server/athenian/api/async_utils.py
- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3348)
> [DEV-5966] Add --db-fetch-cache

- server/tests/controllers/goal_controller/test_goal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3349)
> [DEV-5991] wip merge threshold metrics params

- server/athenian/api/internal/miners/github/precomputed_prs/done_prs.py
- server/athenian/api/internal/miners/github/release_load.py
- server/athenian/api/models/__init__.py
- server/athenian/api/models/sql_builders.pyx
- server/tests/models/test_in_arg_limit.py
- server/tests/models/test_sql_builders.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3350)
> [DEV-5966] Optimize CPU according to profile on acc 205's /histograms

- server/athenian/api/db.py
- server/athenian/api/internal/features/github/unfresh_pull_request_metrics.py
- server/athenian/api/internal/miners/github/pull_request.py
- server/athenian/api/models/__init__.py
- server/athenian/api/models/sql_builders.h
- server/athenian/api/models/sql_builders.pyx
- server/athenian/api/native/cpython.pxd
- server/tests/models/test_sql_builders.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3352)
> [DEV-5966] Accelerate IN (list) and detect SQL injections

- .github/workflows/push.yml
- server/athenian/api/internal/account.py
- server/tests/models/test_sql_builders.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3353)
> [DEV-5552] Execute the main test suite on gitrunners

- server/athenian/api/internal/account.py
- server/athenian/api/internal/features/github/pull_request_metrics.py
- server/athenian/api/internal/miners/github/deployment.py
- server/athenian/api/precompute/__main__.py
- server/athenian/api/precompute/accounts.py
- server/tests/internal/miners/github/test_deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3355)
> [DEV-5996] Reset broken deployments in precomputer

- server/athenian/api/__main__.py
- server/athenian/api/application.py
- server/athenian/api/precompute/accounts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3356)
> [DEV-5941] Print call stack on precomputer timeout

- server/athenian/api/__main__.py
- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3357)
> [DEV-5941] Print asyncio stacks on SIGUSR1

- server/athenian/api/internal/miners/github/precomputed_prs/done_prs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3358)
> [DEV-5999] Delete force-push-dropped PRs in batches

- server/athenian/api/controllers/backoffice_controller.py
- server/athenian/api/internal/miners/github/branches.py
- server/athenian/api/native/sorted_intersection.h
- server/athenian/api/precompute/accounts.py
- server/tests/controllers/miners/github/test_branches.py
- server/tests/controllers/test_share_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3359)
> [DEV-5941] Force full resync of branches in the precomputer

- server/athenian/api/internal/features/jira/issue_metrics.py
- server/tests/controllers/align/test_metric_controller.py
- server/tests/controllers/goal_controller/test_measure_goals.py
- server/tests/controllers/test_jira_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3370)
> [DEV-6030] Adjust jira issue resolution by released PRs in /metrics

- server/athenian/api/__main__.py
- server/athenian/api/application.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3373)
> [DEV-6043] Fix aiohttp access log with frozen time

- server/athenian/api/internal/miners/github/deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3374)
> [DEV-6049] Support logical repositories in the dupe commit deployments

- server/athenian/api/internal/miners/github/precomputed_prs/__init__.py
- server/athenian/api/internal/miners/github/precomputed_prs/done_prs.py
- server/athenian/api/precompute/accounts.py
- server/tests/internal/miners/github/precomputed_prs/test_precomputed_prs.py
Fix the recurrent done PR facts deletions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3375)
> [DEV-6049] Update precomputed force-push-dropped PRs instead of deleting

- server/athenian/api/align/goals/measure.py
- server/athenian/api/controllers/align/metric_controller.py
- server/athenian/api/controllers/jira_controller.py
- server/athenian/api/internal/jira.py
- server/athenian/api/internal/miners/filters.py
- server/athenian/api/models/web/base_model_.py
- server/athenian/api/models/web/calculated_jira_metric_values.py
- server/athenian/api/models/web/jira_metrics_request.py
- server/tests/controllers/jira_controller/test_calc_metrics_jira_linear.py
- server/tests/internal/test_jira.py
- server/tests/testutils/factory/wizards.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3371)
> [DEV-5735] metrics jira controller multiple groups

- server/athenian/api/internal/miners/github/precomputed_prs/done_prs.py
- server/tests/internal/miners/github/precomputed_prs/test_precomputed_prs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3377)
> [DEV-6049] Delete duplicate PRs before force-push-dropping them

- server/athenian/api/internal/miners/github/deployment.py
- server/tests/internal/miners/github/test_deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3378)
> [DEV-6057] Do not reset commits owned by failed deployments

- server/athenian/api/internal/miners/github/label.py
- server/athenian/api/internal/miners/github/release_mine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3379)
> [DEV-6050] Start loading PR labels and extended details earlier in mine_releases()

- server/athenian/api/metadata.py
- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3390)
> Start 0.19.x

- server/athenian/api/internal/miners/github/branches.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3394)
> [DEV-6075] Fix the performance of repo-less branch fetches

- server/athenian/api/controllers/jira_controller/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3393)
> [DEV-6072] Split jira_controller module

- .github/workflows/push.yml
- server/athenian/api/internal/miners/github/deployment_light.py
- server/athenian/api/internal/miners/github/pull_request.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3396)
> [DEV-6075] Speedup /filter/pull_requests: lazy deps + fixed jira

- server/athenian/api/controllers/search_controller/search_prs.py
- server/athenian/api/internal/features/entries.py
- server/athenian/api/internal/features/github/unfresh_pull_request_metrics.py
- server/athenian/api/internal/miners/github/precomputed_prs/done_prs.py
- server/athenian/api/internal/miners/github/pull_request.py
- server/athenian/api/sorted_ops.pyx
- server/athenian/api/sparse_mask.py
- server/setup.py
- server/tests/internal/miners/github/precomputed_prs/test_precomputed_prs.py
- server/tests/internal/miners/github/test_pull_request.py
- server/tests/test_sorted_ops.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3397)
> [DEV-6075] Speedup /search/pull_requests by loading PR numbers earlier

- server/athenian/api/internal/features/entries.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3399)
> [DEV-6075] Fix caching /search/pull_requests

- .github/workflows/push.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3400)
> [DEV-6081] fix docker image root password

- server/athenian/api/internal/miners/jira/issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3402)
> [DEV-6075] Hammer HashJoin to query_jira_raw() in athenian_issue filters

- server/tests/controllers/jira_controller/test_calc_metrics_jira_linear.py
- server/tests/controllers/metrics_controller/test_calc_metrics_prs.py
- server/tests/controllers/metrics_controller/test_calc_metrics_releases.py
- server/tests/controllers/test_metrics_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3404)
> [DEV-5981] forbid metrics request empty granularities

- server/athenian/api/internal/features/jira/issue_metrics.py
- server/athenian/api/internal/miners/jira/issue.py
- server/athenian/api/models/metadata/jira.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3405)
> [DEV-6094] Fix working with jira issue commenters

- server/athenian/api/__main__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3407)
> [DEV-6092] Stop taking transactions for each query

- server/athenian/api/precompute/context.py
- server/requirements.txt
- server/tests/conftest.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3408)
> [DEV-6092] Replace pgbouncer_transaction with pgbouncer_statement

- server/athenian/api/internal/miners/github/precomputed_releases.py
- server/athenian/api/internal/miners/github/release_mine.py
- server/athenian/api/precompute/accounts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3410)
> [DEV-6077] Set all PRs released by specific node ID as release ignored

- server/athenian/api/internal/miners/github/precomputed_prs/done_prs.py
- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3411)
> [DEV-6104] Optimize load_precomputed_pr_releases()

- server/athenian/api/models/__init__.py
- server/athenian/api/models/metadata/github.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3424)
> [DEV-6103] Mitigate spurious bind parameters inside IN (...) strings

- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3421)
> [DEV-5972] Update morcilla and SQLAlchemy to latest 1.x version

- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3425)
> [DEV-6119] Skip edge diff health metrics measurement

- server/athenian/api/internal/features/entries.py
- server/athenian/api/internal/features/metric_calculator.py
- server/tests/controllers/jira_controller/test_calc_metrics_jira_linear.py
- server/tests/controllers/metrics_controller/test_calc_metrics_releases.py
- server/tests/internal/features/test_metric_calculator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3403)
> [DEV-5738] metrics jira labels grouping

- server/athenian/api/controllers/jira_controller/__init__.py
- server/athenian/api/controllers/search_controller/__init__.py
- server/athenian/api/controllers/search_controller/search_jira_issues.py
- server/athenian/api/controllers/search_controller/search_prs.py
- server/athenian/api/internal/with_.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/jira_filter_with.py
- server/athenian/api/models/web/search_jira_issues.py
- server/tests/controllers/search_controller/test_search_jira_issues.py
- server/tests/internal/miners/jira/test_issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3427)
> [DEV-5672] search jira issues endpoint basic

- server/athenian/api/models/__init__.py
- server/athenian/api/models/state/data_52d75707d837_change_github_node_ids.py
- server/athenian/api/models/state/data_629eb7d5cc3b_reposet_node_ids.py
- server/athenian/api/models/state/data_team_member_ids.py
- server/tests/conftest.py
- server/tests/controllers/conftest.py
- server/tests/controllers/test_events_controller.py
- server/tests/controllers/test_filter_controller.py
- server/tests/controllers/test_invitation_controller.py
- server/tests/controllers/test_reposet_controller.py
- server/tests/controllers/test_security_controller.py
- server/tests/controllers/test_settings_controller.py
- server/tests/controllers/test_share_controller.py
- server/tests/controllers/test_team_controller.py
- server/tests/controllers/test_user_controller.py
- server/tests/internal/features/github/test_pull_request_filter.py
- server/tests/internal/features/github/test_pull_request_metrics.py
- server/tests/internal/features/github/test_unfresh.py
- server/tests/internal/miners/github/precomputed_prs/test_precomputed_prs.py
- server/tests/internal/miners/github/test_branches.py
- server/tests/internal/miners/github/test_consistency_torture_commits.py
- server/tests/internal/miners/github/test_deployment.py
- server/tests/internal/miners/github/test_pull_request.py
- server/tests/internal/miners/github/test_release.py
- server/tests/internal/miners/github/test_release_match.py
- server/tests/internal/test_jira.py
- server/tests/models/test_in_arg_limit.py
- server/tests/test_async_utils.py
- server/tests/test_db_performance.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3429)
> [DEV-5972] sa2 compat work

- server/athenian/api/controllers/backoffice_controller.py
- server/athenian/api/internal/features/metric_calculator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3431)
> [DEV-6128] Reset installation event IDs cache in metadata_account target

- server/athenian/api/controllers/backoffice_controller.py
- server/athenian/api/internal/account.py
- server/tests/controllers/test_metrics_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3432)
> [DEV-6128] Reset get_account_organizations for metadata_account target

- server/athenian/api/controllers/search_controller/search_jira_issues.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3434)
> Regain 3.10 compatibility

- server/athenian/api/internal/miners/github/deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3435)
> [DEV-6135] Detect broken PR deployments additionally to commits

- server/athenian/api/internal/miners/github/deployment.py
- server/athenian/api/internal/miners/github/release_load.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3436)
> [DEV-6139] Use a lighter fetch of first-parent commits in ReleaseMatcher

- server/athenian/api/internal/miners/filters.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/jira_filter.py
- server/athenian/api/models/web/jira_status.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3437)
> [DEV-5672] jira filter status categories

- server/athenian/api/internal/miners/jira/issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3438)
> [DEV-6153] Optimize _fill_issues_with_mapped_prs_info()

- server/athenian/api/controllers/search_controller/common.py
- server/athenian/api/controllers/search_controller/search_jira_issues.py
- server/athenian/api/controllers/search_controller/search_prs.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/search_jira_issues.py
- server/athenian/api/models/web/search_prs.py
- server/tests/controllers/search_controller/test_search_jira_issues.py
- server/tests/testutils/factory/metadata.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3439)
> [DEV-5672] search jira issues endpoint

- server/athenian/api/internal/miners/jira/issue.py
- server/tests/internal/features/test_entries.py
- server/tests/internal/miners/jira/test_issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3448)
> [DEV-6156] Fix caching of jira labels for pull request facts

- server/athenian/api/controllers/jira_controller/__init__.py
- server/tests/controllers/test_jira_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3452)
> [DEV-6160] fix caching for filter jira controller

- server/athenian/api/controllers/jira_controller/__init__.py
- server/athenian/api/controllers/jira_controller/common.py
- server/athenian/api/controllers/jira_controller/get_jira_issues.py
- server/athenian/api/models/metadata/jira.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/get_jira_issues.py
- server/tests/controllers/jira_controller/test_get_jira_issues.py
- server/tests/testutils/factory/metadata.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3453)
> [DEV-6149] get jira issues include jira users

- server/athenian/api/controllers/jira_controller/__init__.py
- server/athenian/api/controllers/jira_controller/common.py
- server/athenian/api/controllers/jira_controller/get_jira_issues.py
- server/athenian/api/models/web/get_jira_issues.py
- server/tests/controllers/jira_controller/test_get_jira_issues.py
- server/tests/testutils/factory/metadata.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3454)
> [DEV-6151] get jira issues include GitHub users

- server/athenian/api/controllers/jira_controller/get_jira_issues.py
- server/tests/controllers/jira_controller/test_get_jira_issues.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3455)
> [DEV-6072] Do not return NaN in get_jira_issues operation

- server/athenian/api/models/web/goal.py
- server/athenian/api/serialization.py
- server/tests/align/mutations/test_goals.py
- server/tests/controllers/goal_controller/test_goal.py
- server/tests/test_serialization.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3457)
> [DEV-6167] fix metricvalue invalid type deserialization

- server/athenian/api/internal/features/github/check_run_metrics_accelerated.pyx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3458)
> Avoid undefined call to __builtin_clzl

- server/athenian/api/controllers/goal_controller/goal.py
- server/tests/controllers/goal_controller/test_goal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3461)
> [DEV-6179] Add missing metrics for threshold validation on goal update

- server/athenian/api/controllers/invitation_controller.py
- server/athenian/api/controllers/settings_controller.py
- server/athenian/api/internal/miners/github/bots.py
- server/athenian/api/internal/miners/github/check_run.py
- server/athenian/api/internal/miners/github/commit.py
- server/athenian/api/internal/miners/github/contributors.py
- server/athenian/api/internal/miners/github/deployment.py
- server/athenian/api/internal/miners/github/deployment_light.py
- server/athenian/api/internal/miners/github/developer.py
- server/athenian/api/internal/miners/github/precomputed_prs/done_prs.py
- server/athenian/api/internal/miners/github/precomputed_prs/merged_prs.py
- server/athenian/api/internal/miners/github/precomputed_releases.py
- server/athenian/api/internal/miners/github/pull_request.py
- server/athenian/api/internal/miners/github/release_load.py
- server/athenian/api/internal/miners/github/release_match.py
- server/athenian/api/internal/miners/github/repository.py
- server/athenian/api/internal/miners/jira/issue.py
- server/athenian/api/models/metadata/github.py
- server/athenian/api/models/metadata/jira.py
- server/tests/controllers/test_pagination_controller.py
- server/tests/controllers/test_settings_controller.py
- server/tests/internal/miners/github/precomputed_prs/test_precomputed_prs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3460)
> [DEV-6105] more sqlalchemy2 compatibility

- server/athenian/api/internal/miners/jira/issue.py
- server/tests/internal/miners/jira/test_issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3471)
> [DEV-6031] jira issues filter by pr release

- server/athenian/api/controllers/jira_controller/__init__.py
- server/athenian/api/controllers/jira_controller/common.py
- server/athenian/api/controllers/jira_controller/get_jira_issues.py
- server/tests/controllers/test_jira_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3473)
> [DEV-6215] Fix missing release_settings in filter_jira_stuff

- .github/workflows/push.yml
- server/pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3489)
> Bandit exclude huge file

- server/athenian/api/align/goals/templates.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3490)
> [DEV-6227] Add jira life time goal

- server/athenian/api/controllers/search_controller/search_prs.py
- server/tests/controllers/search_controller/test_search_prs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3492)
> [DEV-6169] Ignore empty jira filter in search_prs controller

- server/athenian/api/internal/miners/jira/issue.py
- server/tests/internal/miners/jira/test_issue.py
- server/tests/testutils/factory/wizards.py
This improve performance for accounts having multiple github accounts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3477)
> [DEV-6221] Use union all when fetching prs mapped to jira issues

- server/athenian/api/internal/features/entries.py
- server/tests/internal/miners/jira/test_issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3476)
> [DEV-6120] Avoid pandas in import_components_as_labels

- server/athenian/api/internal/miners/jira/issue.py
- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3494)
> [DEV-6235] Fix crash in /filter/jira

- server/tests/controllers/test_jira_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3495)
> [DEV-6235] Add the unit test for fast lane filter jira with multiple subqueries

- server/athenian/api/cache.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3496)
> [DEV-6238] Drop caches with pandas

- server/athenian/api/controllers/jira_controller/common.py
- server/athenian/api/controllers/jira_controller/get_jira_issues.py
- server/athenian/api/models/metadata/__init__.py
- server/athenian/api/models/metadata/jira.py
- server/athenian/api/models/web/get_jira_issues.py
- server/athenian/api/models/web/jira_epic_issue_common.py
- server/tests/controllers/jira_controller/test_get_jira_issues.py
~Review but not merge.~
~Required mdb version is in staging but not in production.~
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3475)
> [DEV-6170] get jira issues support description

- server/athenian/api/cache.py
- server/athenian/api/internal/miners/github/pull_request.py
- server/athenian/api/internal/miners/github/release_mine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3498)
> [DEV-6252] Fix the usage of skip_leading_zeros in in1d_str

- server/athenian/api/internal/miners/github/deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3499)
> [DEV-6254] Fix mining deployments with release notifications and no fresh releases

- server/athenian/api/internal/miners/github/branches.py
- server/athenian/api/internal/miners/github/pull_request.py
- server/athenian/api/internal/miners/github/release_match.py
- server/athenian/api/internal/miners/github/release_mine.py
- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3500)
> [DEV-6255] Return back in1d_str()

- server/athenian/api/internal/miners/github/deployment.py
- server/athenian/api/internal/miners/github/rebased_pr.py
- server/tests/internal/miners/github/test_deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3501)
> [DEV-6255] Test the tricky case with deployments with event releases

- server/athenian/api/controllers/jira_controller/__init__.py
- server/athenian/api/controllers/jira_controller/common.py
- server/athenian/api/controllers/jira_controller/get_jira_issues.py
- server/athenian/api/internal/miners/jira/comment.py
- server/athenian/api/models/metadata/jira.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/get_jira_issues.py
- server/athenian/api/models/web/jira_comment.py
- server/athenian/api/models/web/jira_epic_issue_common.py
- server/tests/controllers/jira_controller/test_get_jira_issues.py
- server/tests/internal/miners/jira/test_comment.py
- server/tests/testutils/factory/metadata.py
~Review but not merge.~
~Required mdb version is in staging but not in production.~
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3474)
> [DEV-6146] jira issues comments

- server/athenian/api/controllers/jira_controller/get_jira_issues.py
- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3502)
> [DEV-6259] Debug index duplicates in deployments

- server/athenian/api/application.py
- server/athenian/api/cache.py
- server/athenian/api/internal/miners/github/release_mine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3503)
> [DEV-6260] Make mine_releases() sort releases + fix handling timeouts

- server/athenian/api/controllers/filter_controller.py
- server/athenian/api/internal/miners/github/release_mine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3504)
> [DEV-6260] Fix returning users in /diff/releases

- server/athenian/api/internal/miners/jira/issue.py
- server/requirements.txt
- server/tests/conftest.py
- server/tests/controllers/test_jira_controller.py
- server/tests/internal/miners/github/test_deployment.py
- server/tests/internal/miners/jira/test_issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3505)
> [DEV-6261] Optimize loading Jira issues by released PRs

- server/athenian/api/internal/miners/github/precomputed_prs/done_prs.py
- server/athenian/api/internal/miners/github/repository.py
- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3506)
> [DEV-6261] Tune the SQL performance of done_pull_request_facts

- server/athenian/api/internal/miners/github/release_load.py
- server/athenian/api/internal/miners/github/repository.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3508)
> [DEV-6261] Faster SQL in /filter/repositories

- server/athenian/api/controllers/events_controller.py
- server/athenian/api/models/web/__init__.py
- server/athenian/api/models/web/deployment_notification.py
- server/tests/controllers/test_events_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3507)
> [DEV-5443] deployment labels endpoints stubs

- server/athenian/api/internal/dashboard.py
- server/athenian/api/internal/team.py
- server/tests/controllers/test_team_controller.py
- server/tests/internal/test_dashboard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3510)
> [DEV-6246] clear charts group by on team deletion

- server/athenian/api/db.py
- server/athenian/api/precompute/__main__.py
- server/athenian/api/precompute/accounts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3519)
> [DEV-6261] Dump the edits related to performance

- server/athenian/api/internal/miners/github/commit.py
- server/athenian/api/internal/miners/github/dag_accelerated.h
- server/athenian/api/internal/miners/github/dag_accelerated.pyx
- server/athenian/api/internal/miners/github/release_match.py
- server/athenian/api/internal/miners/github/release_mine.py
- server/tests/internal/miners/github/test_dag_accelerated.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3520)
> [DEV-6261] Optimize _extract_released_commits() on acc 205

- .github/workflows/push.yml
- server/athenian/api/internal/miners/github/dag_accelerated.pyx
- server/athenian/api/internal/miners/github/pull_request.py
- server/athenian/api/models/metadata/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3521)
> [DEV-6287] Fix the SQL performance of _fetch_prs_by_filters()

- server/athenian/api/internal/miners/github/dag_accelerated.pyx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3523)
> [DEV-6297] Fix _extract_released_commits() on zero heads

- server/athenian/api/internal/miners/github/release_load.py
- server/athenian/api/internal/miners/github/release_match.py
- server/athenian/api/internal/miners/github/release_mine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3524)
> [DEV-6299] Do not load commit DAGs twice in mine_releases()

- server/athenian/api/internal/miners/github/release_load.py
- server/tests/internal/miners/github/test_release.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3525)
> [DEV-6301] Do not crash on resolved event releases without URL

- server/athenian/api/internal/miners/github/release_load.py
- server/tests/controllers/test_filter_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3526)
> [DEV-6302] Fix the regression in match_releases_by_branch()

- server/athenian/api/controllers/goal_controller/goal_template.py
- server/tests/controllers/goal_controller/test_goal_template.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3528)
> [DEV-6284] Hide pr-all-mapped-to-jira goal template if jira is not avail

- server/tests/internal/miners/github/test_release.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3527)
> [DEV-6302] Test the edge cases in match_releases_by_branch()

- server/athenian/api/controllers/search_controller/search_jira_issues.py
- server/athenian/api/models/web/search_jira_issues.py
- server/tests/controllers/search_controller/test_search_jira_issues.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3532)
> [DEV-6306] search jira issues order by updated

- server/athenian/api/internal/team.py
- server/athenian/api/internal/team_sync.py
- server/athenian/api/models/state/versions/da4840f77a73_root_teams.py
- server/athenian/api/precompute/accounts.py
- server/tests/controllers/test_backoffice_controller.py
- server/tests/internal/test_account.py
- server/tests/internal/test_team.py
- server/tests/internal/test_team_sync.py
- server/tests/precompute/test_accounts.py
- server/tests/testutils/factory/metadata.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3533)
> [DEV-6316] root team name use GitHub org

- server/athenian/api/controllers/jira_controller/common.py
- server/athenian/api/hacks/show_logged_query.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3534)
> [DEV-6335] hint queries jira issues

- server/athenian/api/internal/miners/jira/issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3535)
> [DEV-6335] Add hint in _fill_issues_with_mapped_prs_info query

- server/athenian/api/internal/miners/github/deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3559)
> [DEV-6403] Fix mismatching columns in extended pr deployments

- server/athenian/api/controllers/events_controller/deployment_labels.py
- server/athenian/api/internal/deployment_labels.py
- server/athenian/api/internal/miners/github/deployment.py
- server/athenian/api/internal/settings.py
- server/tests/internal/miners/github/test_deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3549)
> [DEV-6368] move invalidate pdb deploy func

- server/athenian/api/models/persistentdata/env.py
- server/athenian/api/models/persistentdata/models.py
- server/tests/controllers/events_controller/test_deployments.py
- server/tests/internal/miners/github/test_deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3546)
> [DEV-6264] fix rdb models typo

- server/athenian/api/controllers/jira_controller/common.py
- server/athenian/api/internal/miners/github/precomputed_prs/done_prs.py
- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3561)
> [DEV-6399] Optimize load_precomputed_done_candidates()

- server/athenian/api/internal/miners/github/commit.py
- server/athenian/api/internal/miners/jira/issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3562)
> [DEV-6399] Solve performance bugs in query_jira_raw()

- .github/workflows/push.yml
- server/athenian/api/internal/logical_accelerated.pyx
- server/athenian/api/internal/miners/github/check_run_accelerated.pyx
- server/athenian/api/internal/miners/github/precomputed_prs/utils_accelerated.h
- server/athenian/api/internal/miners/github/precomputed_prs/utils_accelerated.pyx
- server/athenian/api/native/mi_heap_destroy_stl_allocator.h
- server/athenian/api/native/mi_heap_destroy_stl_allocator.pxd
- server/requirements-test.txt
- server/tests/controllers/test_invitation_controller.py
- server/tests/internal/miners/github/precomputed_prs/test_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3565)
> [DEV-6373] Support unicode branch names in triage_by_release_match()

- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3567)
> [DEV-6430] Fix reporting inconsistencies in precomputer

- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3568)
> [DEV-6430] Fix requesting Prometheus metrics in precomputer

- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3570)
> [DEV-6430] Handle duplicate Prometheus metrics in precomputer

- server/athenian/api/db.py
- server/requirements.txt
- server/tests/controllers/test_invitation_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3571)
> [DEV-6431] Add query header with account ID

- server/athenian/api/db.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3573)
> [DEV-6431] Fix _generate_tags() without transaction

- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3574)
> [DEV-6430] Support multiple metadata accounts in inconsistencies

- server/athenian/api/cache.py
- server/athenian/api/internal/features/entries.py
- server/athenian/api/internal/features/github/code.py
- server/athenian/api/internal/miners/github/commit.py
- server/tests/internal/features/github/test_code_metrics.py
- server/tests/internal/miners/github/test_commit.py
- server/tests/test_cache.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3577)
> [DEV-6436] Fix caching /metrics/code*

- server/athenian/api/precompute/store_external_health.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3578)
> [DEV-6400] Filter inconsistency metrics by instance label

- server/athenian/api/precompute/__main__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3588)
> [DEV-6400] Fix setrlimit in precomputer

- server/athenian/api/internal/miners/jira/issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3591)
> [DEV-6237] Enforce athenian_issue_updated_resolved in query_jira_raw()

- server/athenian/api/__main__.py
- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3590)
> [DEV-6237] Replace bootstrapped with bootstrapped-ng

- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3592)
> [DEV-6431] Upgrade asyncpg-rkt

- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3593)
> Bump especifico

- server/athenian/api/defer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3594)
> [DEV-6454] Fix the regression in defer()

- server/athenian/api/controllers/filter_controller.py
- server/athenian/api/internal/features/github/pull_request_filter.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3595)
> [DEV-6456] Support returning deployed components with unresolved commits

- server/athenian/api/models/state/models.py
- server/athenian/api/models/state/versions/83c6782f7737_stale_account_flag.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3596)
> [DEV-6461] Add "stale" flag to the accounts table

- server/athenian/api/controllers/events_controller/deployments.py
- server/athenian/api/internal/user.py
- server/athenian/api/models/web/account_status.py
- server/tests/controllers/test_invitation_controller.py
- server/tests/controllers/test_user_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3597)
> [DEV-6461] Expose and check Account.stale

- server/athenian/api/internal/miners/github/deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3599)
> [DEV-6457] Do not crash on deployments with non-existent commits

- server/athenian/api/internal/miners/github/deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3602)
> [DEV-6457] Do not crash on 0 deployments in the time window

- server/athenian/api/db.py
- server/athenian/api/internal/miners/github/contributors.py
- server/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3603)
> [DEV-6468] Optimize contributors from merged PRs

- server/athenian/api/internal/miners/github/release_load.py
- server/athenian/api/precompute/accounts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3605)
> [DEV-6468] Load branch releases of tag_or_branch repos matched to tags in precomputer

- server/athenian/api/internal/miners/github/release_load.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3606)
> [DEV-6468] Fix loading releases with dags for 0 repos

- server/athenian/api/internal/miners/github/release_mine.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3608)
> [DEV-6472] Do not crash on missing released PRs

- server/athenian/api/hacks/show_body.py
- server/athenian/api/internal/account.py
- server/athenian/api/internal/miners/github/branches.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3612)
> [DEV-6478] Specify the rows count hint in branches

- .github/workflows/push.yml
- server/athenian/api/controllers/backoffice_controller.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3630)
> Fix clearing of jira caches in /reset endpoint

- .github/workflows/push.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3631)
> Restore github actions pull_request_target event

- server/athenian/api/internal/miners/github/precomputed_prs/done_prs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3632)
> Handle rebased PRs in detect_force_push_dropped_prs

- .github/workflows/push.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3670)
> Update actions/cache ofrom v3.3.1 to v4.0.0 due to deprecation

- .github/workflows/push.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3672)
> Temporary push docker image on pr

- .github/workflows/push.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3674)
> Ci cleanup

- server/athenian/api/controllers/settings_controller.py
- server/athenian/api/internal/jira.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3675)
> Duplicated team members

- .github/workflows/push.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3676)
> Make CI lighter

- .github/workflows/push.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3678)
> Restore docker push, keep pubsub-publish disabled
