.gitignore, Makefile
Before this PR is merged, the `db.sqlite` is generated in a place out of the `.gitignore`, so it tries to be committed. If this PR is merged, it will be generated as the `.gitignore` expects.
=> Ignore fixtures and ci dir

Makefile, server/README.md
When using `make run-api` an `.env` file will be automatically created with a placeholder for Sentry values. If they're filled with Athenian Sentry account values, issues locally found will be automatically sent to Athenian Sentry account.
=> Add Sentry conf to docs and 'make run-api'

server/athenian/api/auth.py
Fix [[ENG-140]] after #46
Since #46 changed `User` signature, this commit will use it in the short circuit preparing the user.
I guessed the values for the new `User` from [#46/server/tests/controllers/conftest.py::Line52](https://github.com/athenianco/athenian-api/pull/46/files#diff-e7ee7ee4c3433d161d4e0b9902266965R53)
[ENG-140]: https://athenianco.atlassian.net/browse/ENG-140
=> Fix User short circuit after changing its signature

Makefile, server/README.md
supersedes #66
to clean local fixtures:
```
$ make clean
```
to run your own API docker image:
```
$ IMAGE=your_api_image:tag make run-api
```
=> Help development with clean command and docs

server/athenian/api/controllers/security_controller.py, server/athenian/api/openapi/openapi.yaml, server/tests/controllers/conftest.py, server/tests/controllers/test_cors.py, server/tests/controllers/test_invitation_controller.py, server/tests/controllers/test_metrics_controller.py, server/tests/controllers/test_repository_set_controller.py, server/tests/controllers/test_user_controller.py
This change is required for generating the client for making it able to call with bearer token.
I tried generating the python files and on changes occurred.
Reference: https://swagger.io/docs/specification/authentication/bearer-authentication/
=> Add bearerAuth in openapi spec for autheniticated path

Makefile, server/athenian/api/__init__.py, server/athenian/api/controllers/invitation_controller.py, server/athenian/api/invite_admin.py, server/athenian/api/models/state/models.py, server/athenian/api/models/state/versions/a8d2bdb184f0_create_invitations_table.py, server/athenian/api/models/state/versions/e7afe365ab0e_create_repository_sets_table.py, server/tests/controllers/conftest.py, server/tests/controllers/test_invitation_controller.py, server/tests/gen_sqlite_db.py
Changes default admin backdoor index to 0.
The reason I did this is that I wasn't able to test userflow handshake webapp <> api due to an error when calling `/v1/accept`. The error was a `LockedError`. The problem is that when generating the admin link with the default admin backdoor account with the "special" id, since the `id` is an autoincrement by default, the api was returning an error because was trying to create an new account with `id = admin_backdoor + 1`. Changing it to `0` (that IMHO is still special enough), fixed the problem.
Alternatives that I considered:
- adding a field in `Account` like `is_backdoor`, but it seemed to be an overkill for just this case,
- resetting the auto increment when creating the special backdoor account, but it's backend specific.
=> Admin backdoor index

server/athenian/api/create_default_user.py, server/athenian/api/metadata.py
This fix this issue
```bash
$ make gkwillie 
docker run --rm -e DB_DIR=/io -v/data/src/athenian/athenian-api/server/tests:/io --env-file .env --entrypoint python3 athenian/api:dev -m athenian.api.create_default_user sqlite:///io/sdb.sqlite
Traceback (most recent call last):
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/server/athenian/api/create_default_user.py", line 30, in <module>
exit(main())
File "/server/athenian/api/create_default_user.py", line 19, in main
session.add(UserAccount(Auth0.DEFAULT_USER, acc.id, False))
TypeError: __init__() takes 1 positional argument but 4 were given
make: *** [Makefile:44: gkwillie] Error 1
```
=> Fix function signature from UserAccount

.travis.yml
supersedes https://github.com/athenianco/athenian-api/pull/138
This PR will introduce into Travis build a test to ensure that the autogenerated JS API client won't fail, which can happen as demoed by https://github.com/dpordomingo/athenian-api/pull/4; if that case happens, it will be raised a red flag in Travis [like this one](https://travis-ci.com/dpordomingo/athenian-api/jobs/293797859#L488).
=> Add tests for the Autogenerated API

server/setup.py
I wasn't able to build the cython extension without this imports ordering. See: https://stackoverflow.com/questions/21594925/error-each-element-of-ext-modules-option-must-be-an-extension-instance-or-2-t
I built it by running:
```
python setup.py build_ext --inplace
```
as explained [here](http://docs.cython.org/en/latest/src/quickstart/build.html#building-a-cython-module-using-setuptools).
=> Fix imports in setup.py

docker-compose.yaml, server/README.md, server/tests/load_postgres_data.py
Closes [ENG-389](https://athenianco.atlassian.net/browse/ENG-389).
This PR aims to provide an easy way to run the api with a dump of the real data (`staging` or `production`). This is done with docker compose with 4 containers:
- api
- Memcached (for caching)
- postgres (for `state`, `precomputed` and `metadata` dabases)
- cloud SQL proxy (for connecting to the live environment and dump the databases)
The requirements are:
- docker compose,
- a service account with the corresponding json credentials file to connect to the CloudSQL database,
- the credentials for the CloudSQL databases.
See [here](https://github.com/athenianco/athenian-api/compare/local-development?expand=1#diff-7d62b4cde47a08800e3b7212ca2dd397R145) for more details.
https://streamable.com/fu7abs
Running the api in the …
=> Running api with dump of real data

server/athenian/api/controllers/contributors_controller.py, server/athenian/api/controllers/filter_controller.py, server/athenian/api/controllers/miners/access.py, server/athenian/api/controllers/miners/github/access.py, server/athenian/api/controllers/miners/github/contributors.py, server/athenian/api/openapi/openapi.yaml, server/tests/controllers/miners/github/test_contributors.py, server/tests/controllers/test_contributors_controller.py
This implements the `/contributors/{id}` endpoint and updates the spec file with the actual errors that could be returned.
=> Implement `/contributors/{id}` endpoint

server/athenian/api/hacks/webapp.py
The script provided in this PR emulates the requests that happen during a full refresh of the Overview section of the webapp. You can see the possible flags by running:
```
python server/benchmark.py --help
```
Usage example:
```
python server/benchmark.py --token <bearer token> --days-timedelta 180
```
Output example:
```
=========================
Starting benchmark: [2020-04-18, 2020-10-15], exclude_inactive=True, limit=500, timezone=120, cache_enabled=False
=========================
=========================
-------------------------
https://api.athenian.co/v1/user - 0.60316s
X-Performance-DB: s 0.023, m 0.000, p 0.000
X-Performance-Cache-Misses:
X-Performance-Cache-Ignores:
X-Performance-Cache-Hits:
X-Performance-Precomputed-Hits:
X-Performance-Precomputed-Misses: …
```
=> Add a script to emulate webapp refresh of Overview section

Dockerfile, server/athenian/api/__init__.py, server/requirements.txt
https://github.com/getsentry/sentry-python/issues/858
=> Fix sentry_sdk 0.19.0 crash

server/athenian/api/models/web/team.py, server/athenian/api/models/web/team_create_request.py, server/athenian/api/models/web/team_update_request.py, server/athenian/api/openapi/openapi.yaml, server/tests/controllers/test_team_controller.py
This specification change allows:
- Create a new team with an explicit parent.
- Update a team to set a new parent.
- List the teams with their hierarchy via the new `parent` field.
=> [DEV-1206] Add the Team's parent to the spec

server/MANHOLE.md, server/athenian/api/controllers/user_controller.py, server/athenian/api/models/web/user.py, server/athenian/api/openapi/openapi.yaml, server/tests/controllers/test_user_controller.py
For gods, `User.impersonated_by` exists. It either equals to `User.id` (not active) or the real god ID.
=> [DEV-1234] Add "impersonated_by"to /user

server/athenian/api/controllers/miners/jira/issue.py
Closes [DEV-1646](https://athenianco.atlassian.net/browse/DEV-1646).
=> Fix the caching key generator when no timestamp for JIRA issue

docker-compose.yaml
For some unknown reasons, in pre-staging environment, those containers are exiting with code 0 without anyone stopping them. This should at least make them restart in case it happens.
=> Setup restart policy in docker compose for memcached and cloud sql proxy

server/athenian/api/__main__.py, server/athenian/api/db.py, server/athenian/api/preloading/__main__.py, server/athenian/api/preloading/cache.py
Adds a script to assess memory usage of preloaded DataFrames.
This is the output when ran against prod DB with [this options](https://github.com/athenianco/athenian-api/pull/1337/files#diff-57022c74cc59d401d7a1ec3d23077a91a73f2224a74f9f7b22feea1080189e6bR275):
```
python3 -m athenian.api.preloading --metadata-db=postgresql://***:***@localhost:5435/metadata --state-db=postgresql://***:***@localhost:5435/state --precomputed-db=postgresql://***:***@localhost:5435/precomputed --persistentdata-db=postgresql://***:***@localhost:5435/persistentdata --detailed
- DB: mdb                           | [total: 238.98 MiB]
-- DataFrame: prs                   | [total: 238.98 MiB]
--- Raw                             | [total: 526318360]
--- Raw series
Index                        128
acc_id …
```
=> Preloading tooling

server/athenian/api/controllers/miners/github/pull_request.py, server/athenian/api/controllers/miners/github/release_load.py, server/athenian/api/controllers/miners/github/release_match.py
This PR is a preparatory one to be able to work on [DEV-2148](https://athenianco.atlassian.net/browse/DEV-2148).
The idea is the same as we did for the PR miner: I grouped functions into classes in modules `athenian.api.controllers.miners.github.{release_match,release_load}` so that they can be extended for preloading.
I'd rathered open a separate PR since this is already a pretty big one despite being mostly moving things and changing callers.
=> Overridable PRs to releases and viceversa mappers and releases loader

server/athenian/api/controllers/features/entries.py, server/athenian/api/controllers/features/github/unfresh_pull_request_metrics.py, server/athenian/api/controllers/miners/github/release_load.py, server/athenian/api/experiments/preloading/entries.py, server/athenian/api/preloading/cache.py
Closes [DEV-2148](https://athenianco.atlassian.net/browse/DEV-2148).
Tested with the following:
```
hey \
-H 'Connection: keep-alive' \
-H 'Pragma: no-cache' \
-H 'Cache-Control: no-cache' \
-H 'sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer <evicted>' \
-H 'sec-ch-ua-mobile: ?0' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36' \
-H 'Content-Type: application/json' \
-H 'Origin: http://localhost:3000' \
-H 'Sec-Fetch-Site: same-site' \
-H 'Sec-Fetch-Mode: cors' \
-H 'Sec-Fetch-Dest: empty' \
-H 'Referer: http://localhost:3000/' \
-H 'Accept-Language: en-US,en;q=0.9,it-IT;q=0.8,it;q=0.7' \
-m POST \
-d …
```
=> Preload precomputed release

server/athenian/api/preloading/cache.py
Closes [DEV-2301](https://athenianco.atlassian.net/browse/DEV-2301).
Locally I tested this PR + these two, https://github.com/athenianco/athenian-api/pull/1400, https://github.com/athenianco/athenian-api/pull/1404, to assess the state of preloading.
Of course, memory usage benefits a lot from this change compared to [here](https://github.com/athenianco/athenian-api/pull/1404#issue-633031853) since only Faire is being pre-loaded:
```
```
Analysis on 6 months of data for Faire, with all repos and contribs, running 30 requests with a parallelism of 3 requests.
```
Summary:
Total:	156.0242 secs
Slowest:	21.1123 secs
Fastest:	9.9842 secs
Average:	15.4472 secs
Requests/sec:	0.1923
Response time histogram:
9.984 [1]	|■■■■
11.097 [2]	|■■■■■■■■■
12.210 [0]	|
13.323 [5]	|■■■■■■■■■■■■■■■■■■■■■■ …
```
=> Preload on feature flag only

.github/workflows/push.yml, server/athenian/api/controllers/events_controller.py, server/athenian/api/controllers/features/everything.py, server/athenian/api/controllers/features/github/pull_request_filter.py, server/athenian/api/controllers/features/github/unfresh_pull_request_metrics.py, server/athenian/api/controllers/filter_controller.py, server/athenian/api/controllers/jira_controller.py, server/athenian/api/controllers/miners/github/branches.py, server/athenian/api/controllers/miners/github/contributors.py, server/athenian/api/controllers/miners/github/developer.py, server/athenian/api/controllers/miners/github/precomputed_prs.py, server/athenian/api/controllers/miners/github/pull_request.py, server/athenian/api/controllers/miners/github/release_load.py, server/athenian/api/controllers/miners/github/release_match.py, server/athenian/api/controllers/miners/github/release_mine.py, server/athenian/api/controllers/miners/github/repositories.py, server/athenian/api/controllers/miners/jira/issue.py, server/athenian/api/controllers/pagination_controller.py, server/athenian/api/controllers/settings_controller.py, server/athenian/api/experiments/preloading/entries.py, server/athenian/api/hacks/heat_cache.py, server/athenian/api/hacks/push_copy_releases.py, server/athenian/api/preloading/cache.py, server/tests/conftest.py, server/tests/controllers/conftest.py, server/tests/controllers/miners/github/test_branches.py, server/tests/controllers/miners/github/test_precomputed_prs.py, server/tests/controllers/miners/github/test_pull_request.py, server/tests/controllers/miners/github/test_release.py
- Removes all the re-exported backward-compatible class methods as functions in favor of explicit call,
- All tests previously calling the re-exported functions are now calling the corresponding class method, preloaded or not, depending on the `with_preloading` fixture,
- Adds miners to CI preloading tests.
=> Preloading fix tests

server/athenian/api/controllers/calculator_selector.py, server/athenian/api/experiments/preloading/entries.py, server/athenian/api/preloading/cache.py
In [this PR](https://github.com/athenianco/athenian-api/pull/1548) I implemented a check that consists in ensuring that the data for a given account and/or GH installation id are loaded in memory in order to use preloading metrics calculator.
When testing on `mirror` environment, I realized that this check is not reliable as it was causing some false negatives. For example, some data related to the JIRA mapping were missing because of an account without JIRA data. This was causing the API to think that the data were not preloaded when actually the missing data is expected.
I fixed by tracking directly what are the enabled accounts as loaded in the latest `refresh`.
=> Preloading fixes

server/athenian/api/especifico.py, server/pyproject.toml, server/tests/conftest.py, server/tests/controllers/test_events_controller.py, server/tests/controllers/test_filter_controller.py, server/tests/controllers/test_histograms_controller.py, server/tests/controllers/test_integrations_controller.py, server/tests/controllers/test_jira_controller.py, server/tests/controllers/test_metrics_controller.py, server/tests/controllers/test_pagination_controller.py, server/tests/controllers/test_reposet_controller.py, server/tests/controllers/test_settings_controller.py, server/tests/controllers/test_team_controller.py, server/tests/controllers/test_user_controller.py, server/tests/test_cache.py, server/tests/test_heavy_load.py
Add `validate_responses=True` in tests App to validate all generated responses against their declared schemas.
Often we doesn't honour the schema, for that cases app_validate_responses pytest mark has been created.
Those overrides can be gradually fixed and removed.
=> [DEV-3831] validate responses using schema during tests

server/athenian/api/controllers/team_controller.py, server/tests/conftest.py, server/tests/controllers/test_team_controller.py
This change is required for Align root team creation, but applicable from now since FE should never change the parent of a team.
Also this avoid `created_at` to be reset when updating the team.
=> [DEV-4192] teams forbid unsetting parent

.github/workflows/push.yml
tests/align is now run into fat1 to make distribution fairer.
=> [DEV-4438] Rebalance CI tests split

server/tests/controllers/miners/github/test_release.py
This combination is not supported by design and API already forbids to
set such value.
=> [DEV-4648] Fix xfailing test for branche releases on logical repo

server/athenian/api/internal/reposet.py
We have a test causing this condition with many concurrent request,  this never happened in production.
so an alternative solution is to set LoggingIntegration(event_level=None) for  sentry in CI tests
=> [DEV-4622] no error log on concurrent reposet creation

server/athenian/api/align/models.py, server/athenian/api/align/queries/metrics.py, server/athenian/api/internal/features/entries.py, server/tests/align/queries/test_metrics.py, server/tests/internal/features/test_entries.py
- support  jira filters in `MetricEntriesCalculator.batch_calc*` methods
- support jira filters in `metricCurrentValues` query (where grouping is not needed) 
Related: DEV-4920
=> [DEV-4921] gql current metric values support jira filters

server/athenian/api/__main__.py, server/athenian/api/application.py
These validation errors were already `warning`, so not reported to Sentry`, when running production code.
=> [DEV-5074] Do not report validation error to sentry during tests

server/athenian/api/controllers/jira_controller.py, server/athenian/api/models/web_model_io.pyx, server/tests/models/test_web_model_io.py
Fix model string handling in web_model_io when python unicode representation has more than one byte per code point
=> [DEV-5107] web model io fix multibyte unicodestring

server/athenian/api/align/mutations/goals.py, server/tests/align/mutations/test_goals.py
By assigning and then deleting association we can now unset the last team target and set another.
=> [DEV-5145] Fix the last assigned team check when updating a goal

server/athenian/api/align/goals/templates.py
Make the default TLO template goals user-friendly with proper names. I also removed 2 minor TLO template goals form the default config that are minor, to reduce the noise in the UI for now.
Signed-off-by: Waren Long <waren@athenian.co>
=> [DEV-4948] Add TLO template names

server/athenian/api/controllers/events_controller.py, server/athenian/api/internal/features/entries.py, server/athenian/api/precompute/accounts.py, server/tests/conftest.py, server/tests/controllers/features/github/test_pull_request_filter.py, server/tests/controllers/features/github/test_pull_request_metrics.py, server/tests/controllers/features/github/test_unfresh.py, server/tests/controllers/miners/github/test_precomputed_prs.py, server/tests/controllers/miners/github/test_pull_request.py, server/tests/controllers/miners/github/test_release.py, server/tests/controllers/test_filter_controller.py, server/tests/controllers/test_jira_controller.py, server/tests/controllers/test_settings_controller.py, server/tests/internal/features/test_entries.py, server/tests/internal/miners/jira/test_issue.py
Extract `PRFactsCalculator` from `MetricsCalculator`, so that only `PRFactsCalculator` is built when you only need to call `calc_pull_request_facts_github`
=> [DEV-5347] Extract PRFactsCalculator from MetricEntriesCalculator

Dockerfile, patches/cpython_configure_ac.patch, patches/cpython_makefile.patch, patches/cpython_rules.patch
Using the patch adapted from https://github.com/python/cpython/pull/95908
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3040)
=> [DEV-5385] Build CPython using BOLT

server/athenian/api/auth.py, server/athenian/api/controllers/histograms_controller.py, server/athenian/api/controllers/metrics_controller.py, server/athenian/api/defer.py, server/athenian/api/experiments/idmatching/make_dataset.py, server/athenian/api/experiments/indexing/indexer.py, server/athenian/api/models/precomputed/schema_monitor.py, server/requirements-lint.txt, server/tests/controllers/features/github/test_deployment_metrics.py, server/tests/controllers/miners/github/test_precomputed_prs.py, server/tests/internal/miners/jira/test_issue.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3096)
=> Upgrade flake8 + pycodestyle

server/athenian/api/align/goals/dbaccess.py, server/athenian/api/align/goals/measure.py, server/athenian/api/controllers/align/metric_controller.py, server/athenian/api/controllers/goal_controller.py, server/athenian/api/controllers/search_controller/search_prs.py, server/athenian/api/internal/logical_repos.py, server/athenian/api/internal/miners/github/pull_request.py, server/athenian/api/internal/repos.py, server/athenian/api/internal/settings.py, server/athenian/api/models/state/models.py, server/tests/align/goals/test_dbaccess.py, server/tests/controllers/test_prefixer.py, server/tests/internal/test_logical_repos.py, server/tests/internal/test_repos.py
Moved parse/dump/resolved goal repositories functions outside of goals module
Also use `prefixer.dereference_repositories(references)` in `dereference_db_repositories` to avoid code repetition
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3166)
=> [DEV-5582] refactor db repositories access

server/requirements.txt
In order to avoid external HTTP request when serving private spec JSON.
https://github.com/athenianco/especifico/pull/110/files
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3222)
=> [DEV-5700] Update especifico to 3.0.28

server/athenian/api/object_arrays.pyx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3336)
=> [DEV-5946] Fix objects_to_pyunicode_bytes() digest non-contiguous arrays

server/athenian/api/internal/miners/github/deployment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3391)
=> [DEV-6064] Fix the error logging of non-string deployment names

server/athenian/api/internal/features/jira/issue_metrics.py, server/tests/controllers/align/test_metric_controller.py, server/tests/controllers/jira_controller/test_calc_metrics_jira_linear.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athenianco/athenian-api/3406)
=> [DEV-6100] Avoid zero division for jira-resolution-rate metric

server/athenian/api/application.py, server/athenian/api/auth.py, server/athenian/api/internal/refetcher.py, server/athenian/api/kms.py, server/athenian/api/mandrill.py, server/athenian/api/segment.py, server/pyproject.toml, server/requirements-test.txt, server/requirements.txt, server/tests/controllers/test_invitation_controller.py, server/tests/internal/miners/github/test_check_run_benchmark.py
`aiohttp` relies on the `yarl` library for URL parsing and building. When running the tests, the majority of them fail due to a version of `yarl` that is incompatible with `aiohttp`.
The `yarl` requirement in `aiohttp==3.8.4` (current version we have in our requirements) is very loose: https://github.com/aio-libs/aiohttp/blob/v3.8.4/setup.cfg#L56
Indeed when inspecting the Docker container we can check using `pip freeze` that the version of `yarl` installed is `1.18.3`. This is the output of `pipdeptree`:
```
root@f7718d7499e7:/server# pipdeptree --reverse --packages yarl
yarl==1.18.3
└── aiohttp==3.8.4 [requires: yarl>=1.0,<2.0]
├── aiohttp-cors==0.7.0 [requires: aiohttp>=1.1]
├── aiohttp-jinja2==1.5.1 [requires: aiohttp>=3.6.3]
├── gcloud-aio-auth==4.2.1 [requires: …
```
=> Make CI pass
